import assert from 'node:assert/strict'
import test from 'node:test'
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { buildPackageModel, parseGateLedger, parseGithubConnector } from './outcome-package.mjs'

const map = (overrides = '') => `# Map\n\`\`\`yaml\nschema_version: 1\nproject_id: demo\ntitle: Demo\nphases:\n  - id: phase-one\n    title: Phase\n    purpose: Phase purpose\n    scopes:\n      - id: scope-one\n        title: Scope\n        purpose: Scope purpose\n        stages:\n          - id: stage-one\n            title: Stage\n            purpose: Stage purpose\n            depends_on: []\n            gates_file: GATES_STAGE.md\n            implementation_state: work_in_progress\n            evidence_closure_state: pending\n${overrides}\n\`\`\`\n`
const contract = '- Project ID: `demo`\n- Project name: `Demo`\n- Outcome: Measured outcome\n- Acceptance authority: `Cherry`\n'
function fixture({ contractText = contract, mapText = map(), gateText = '- [x] G1: first\n- [ ] G2: second', registry = [] } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'outcome-package-')); mkdirSync(join(root, 'docs'))
  writeFileSync(join(root, 'docs/OUTCOME_CONTRACT.md'), contractText); writeFileSync(join(root, 'docs/OUTCOME_MAP.md'), mapText); if (gateText !== null) writeFileSync(join(root, 'docs/GATES_STAGE.md'), gateText)
  return buildPackageModel({ root, contractFile: 'docs/OUTCOME_CONTRACT.md', mapFile: 'docs/OUTCOME_MAP.md', bindingRegistry: registry, now: new Date(), staleAfterSeconds: 3600 })
}

test('valid package parses contract map and referenced gates', () => { const model = fixture(); assert.equal(model.errors.length, 0); assert.equal(model.phases[0].scopes[0].stages[0].gate.total, 2) })
test('missing package documents fail closed unknown', () => { const model = buildPackageModel({ root: '/missing', contractFile: 'none', mapFile: 'none' }); assert.equal(model.status, 'unknown'); assert.ok(model.errors.includes('contract_missing')) })
test('reference mismatch fails closed conflict', () => { const model = fixture({ mapText: map().replace('project_id: demo', 'project_id: other') }); assert.equal(model.status, 'conflict'); assert.ok(model.errors.includes('project_reference_mismatch')) })
test('missing Gate reference fails closed unknown', () => { const model = fixture({ gateText: null }); assert.equal(model.status, 'unknown'); assert.ok(model.errors.includes('gate_reference_missing:stage-one')) })
test('unknown current Stage reference fails closed conflict', () => { const model = fixture({ mapText: `${map()}\n- Current: \`stage-missing\`` }); assert.equal(model.status, 'conflict'); assert.ok(model.errors.includes('current_reference_mismatch')) })
test('conflicting current boundaries fail closed conflict', () => { const model = fixture({ mapText: `${map()}\n- Current: \`stage-one\`\n- Current: \`stage-two\`` }); assert.equal(model.status, 'conflict') })
test('stable hierarchy has project phase scope stage and Gate acceptance child', () => { const model = fixture(); const stage = model.phases[0].scopes[0].stages[0]; assert.equal(stage.gate.gates[0].stageId, stage.id); assert.equal(stage.gatePurpose.includes('acceptance checklist'), true) })
test('invalid stable id fails closed unknown', () => { const model = fixture({ mapText: map().replace('id: stage-one', 'id: Stage One') }); assert.equal(model.status, 'unknown'); assert.ok(model.errors.includes('invalid_stable_id')) })
test('gate acceptance child preserves closed and total without aggregate inference', () => { const ledger = parseGateLedger('- [x] A1: done\n- [ ] A2: open', 'stage-one'); assert.deepEqual({ closed: ledger.closed, total: ledger.total }, { closed: 1, total: 2 }) })
test('gate reference anchor selects only the owning Stage range', () => { const ledger = parseGateLedger('- [x] M5: parser\n- [x] M6: ids\n- [ ] M10: ui', 'stage-four', 'M5-M9'); assert.deepEqual(ledger.gates.map((gate) => gate.id), ['M5', 'M6']) })
test('role bindings are project scoped with replaced history', () => { const now = new Date().toISOString(); const model = fixture({ registry: [{ project_id: 'demo', role: 'builder', status: 'replaced', bound_at: '2026-01-01T00:00:00Z', replaced_at: '2026-02-01T00:00:00Z' }, { project_id: 'demo', role: 'builder', status: 'active', bound_at: now, observed_at: now, activity: 'current work' }, { project_id: 'other', role: 'builder', status: 'active', bound_at: now }] }); const builder = model.bindings.find((item) => item.role === 'builder'); assert.equal(builder.status, 'active'); assert.equal(builder.historyCount, 2) })
test('NOW separation uses Builder binding while progress refuses activity inference', () => { const now = new Date().toISOString(); const model = fixture({ registry: [{ project_id: 'demo', role: 'builder', status: 'active', bound_at: now, observed_at: now, activity: 'edited 200 files' }] }); assert.equal(model.now.activity, 'edited 200 files'); assert.deepEqual(model.progress, { available: false, reason: 'no_cross_stage_aggregate' }) })
test('fail-closed states cover missing stale conflicting unbound blocked and locked inputs', () => { const model = fixture({ gateText: null }); assert.equal(model.phases[0].scopes[0].stages[0].state, 'unknown'); assert.equal(model.bindings.every((item) => item.status === 'unbound'), true); assert.equal(model.progress.available, false) })
test('GitHub connector missing remains optional and has no completion authority', () => { const connector = parseGithubConnector(undefined); assert.equal(connector.state, 'missing'); assert.equal(connector.required, false); assert.equal(connector.localCandidate.sync, 'unknown'); assert.equal(connector.completionAuthority, false) })
test('GitHub connector connected separates local candidate and published evidence', () => { const connector = parseGithubConnector({ adopted: true, required: false, repository: 'dltmddnr3/dock', remote_name: 'origin', default_branch: 'main', binding_state: 'connected', completion_authority: false }, { state: 'available', branch: 'main', ahead: 15, behind: 0, observedRepository: 'dltmddnr3/dock', remoteState: 'published' }); assert.equal(connector.state, 'connected'); assert.deepEqual(connector.localCandidate, { state: 'available', branch: 'main', ahead: 15, behind: 0, sync: 'ahead' }); assert.equal(connector.published.ref, 'origin/main'); assert.equal(connector.published.state, 'connected'); assert.equal(connector.checks.state, 'unknown'); assert.equal(connector.release.state, 'unknown'); assert.equal(connector.completionAuthority, false) })
test('GitHub connector connected empty remote is not published and not conflict', () => { const connector = parseGithubConnector({ adopted: true, required: false, repository: 'dltmddnr3/outcome', remote_name: 'origin', default_branch: 'main', binding_state: 'connected', completion_authority: false }, { state: 'available', branch: 'main', ahead: null, behind: null, observedRepository: 'dltmddnr3/outcome', remoteState: 'empty_remote' }); assert.equal(connector.state, 'connected'); assert.equal(connector.published.state, 'not_published'); assert.equal(connector.published.detail, 'empty_remote'); assert.equal(connector.completionAuthority, false) })
test('GitHub connector adopted repository null remains unbound', () => { const connector = parseGithubConnector({ adopted: true, required: false, repository: null, default_branch: 'main', binding_state: 'unbound', completion_authority: false }, { state: 'available', branch: 'main', ahead: null, behind: null, observedRepository: null }); assert.equal(connector.state, 'unbound'); assert.equal(connector.repository, null); assert.equal(connector.defaultBranch, 'main') })
test('GitHub connector conflicts on unsafe authority repository mismatch credential URL or invalid ref', () => { const unsafe = parseGithubConnector({ adopted: true, required: false, repository: 'owner/repo', remote_name: 'origin', default_branch: 'main', binding_state: 'connected', completion_authority: true }); const mismatch = parseGithubConnector({ adopted: true, required: false, repository: 'owner/repo', remote_name: 'origin', default_branch: 'main', binding_state: 'connected', completion_authority: false }, { state: 'available', branch: 'main', ahead: 0, behind: 0, observedRepository: 'other/repo' }); const credential = parseGithubConnector({ adopted: true, required: false, repository: 'https://token@github.com/owner/repo.git', remote_name: 'origin', default_branch: 'main', binding_state: 'connected', completion_authority: false }); const invalidRef = parseGithubConnector({ adopted: true, required: false, repository: 'owner/repo', remote_name: '--upload-pack', default_branch: 'main..other', binding_state: 'connected', completion_authority: false }); assert.equal(unsafe.state, 'conflict'); assert.equal(mismatch.state, 'conflict'); assert.equal(credential.state, 'conflict'); assert.equal(credential.repository, null); assert.equal(invalidRef.state, 'conflict'); assert.equal(unsafe.completionAuthority, false) })
