import { useEffect, useMemo, useState, type CSSProperties } from 'react'
import { Check, ChevronLeft, ChevronRight, Circle, Layers3, Radio, RefreshCw } from 'lucide-react'
import { fetchOutcomeDashboard } from '../lib/api'
import { activityLabelKo, axisLabelKo, freshnessLabelKo, gatePresentation, groupPresentation, phasePresentation, projectOutcomePresentation, roleLabel, scopePresentation, sourceLabelKo, sourceStateLabelKo, stagePresentation, stateLabelKo } from './outcomeKorean'

type SourceState = 'valid' | 'stale' | 'unknown' | 'conflict'
export type Binding = { role: string; status: string; activity: string | null; boundAt: string | null; observedAt: string | null; freshness: string; historyCount: number; stageId?: string | null }
type Gate = { id: string; title: string; closed: boolean; groupCode: string }
type GateGroup = { code: string; name: string; total: number; closed: number }
export type PackageStage = { id: string; title: string; purpose: string; dependsOn: string[]; expectedDurationMinutes?: number | null; gatePurpose: string; sourceState: string; state: string; gate: { gates: Gate[]; groups: GateGroup[]; total: number; closed: number; available: boolean; sourceRef: string | null }; axes: { implementation: string; test: string; evidence: string; independentQa: string; cherryAcceptance: string; release: string } }
export type Scope = { id: string; title: string; purpose: string; stages: PackageStage[] }
export type Phase = { id: string; title: string; purpose: string; completion: string | null; scopes: Scope[] }
export type GithubConnector = { adopted: boolean; required: boolean; state: string; repository: string | null; remoteName: string | null; defaultBranch: string | null; completionAuthority: false; localCandidate: { state: string; branch: string | null; ahead: number | null; behind: number | null; sync: string }; published: { state: string; repository: string | null; ref: string | null; detail: string }; checks: { state: string }; release: { state: string } }
export type PackageProject = { status: SourceState; errors: string[]; observedAt: string | null; sourceFreshness?: { state: string; observedAt: string | null }; project: { id: string; name: string; outcome: string; acceptanceAuthority: string }; connectors: { github: GithubConnector }; phases: Phase[]; current: { phaseId: string; scopeId: string; stageId: string } | null; next: { phaseId: string; scopeId: string; stageId: string } | null; bindings: Binding[]; now: { status: string; activity: string | null; observedAt: string | null; source: string }; progress: { available: false; reason: string } }
export type OutcomeDashboardData = { schemaVersion: 2; observedAt: string; build: { repository: string; ref: string; commit: string | null; tree: string | null; asset: string | null; runtimeNowPinned: false }; projects: PackageProject[] }
export type HierarchySelection = { phaseId: string | null; scopeId: string | null; stageId: string | null }

const compactTime = (value: string | null) => value ? new Intl.DateTimeFormat('ko-KR', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '근거 없음'
export function findStage(project: PackageProject, stageId: string | null | undefined) { for (const phase of project.phases) for (const scope of phase.scopes) for (const stage of scope.stages) if (stage.id === stageId) return { phase, scope, stage }; return null }
export function currentHierarchy(project: PackageProject) { const phaseIndex = project.phases.findIndex((phase) => phase.id === project.current?.phaseId); const phase = phaseIndex >= 0 ? project.phases[phaseIndex] : null; const scopeIndex = phase?.scopes.findIndex((scope) => scope.id === project.current?.scopeId) ?? -1; const scope = phase && scopeIndex >= 0 ? phase.scopes[scopeIndex] : null; const stageIndex = scope?.stages.findIndex((stage) => stage.id === project.current?.stageId) ?? -1; const stage = scope && stageIndex >= 0 ? scope.stages[stageIndex] : null; return { phase, scope, stage, phaseIndex: phaseIndex + 1, phaseTotal: project.phases.length, scopeIndex: scopeIndex + 1, scopeTotal: phase?.scopes.length ?? 0, stageIndex: stageIndex + 1, stageTotal: scope?.stages.length ?? 0 } }

export function defaultHierarchySelection(project: PackageProject): HierarchySelection { const phase = project.phases.find((item) => item.id === project.current?.phaseId) ?? project.phases[0] ?? null; const scope = phase?.scopes.find((item) => item.id === project.current?.scopeId) ?? phase?.scopes[0] ?? null; const stage = scope?.stages.find((item) => item.id === project.current?.stageId) ?? scope?.stages[0] ?? null; return { phaseId: phase?.id ?? null, scopeId: scope?.id ?? null, stageId: stage?.id ?? null } }
export function selectHierarchyPhase(project: PackageProject, phaseId: string): HierarchySelection { const phase = project.phases.find((item) => item.id === phaseId) ?? project.phases[0] ?? null; const scope = phase?.scopes.find((item) => item.id === project.current?.scopeId) ?? phase?.scopes[0] ?? null; const stage = scope?.stages.find((item) => item.id === project.current?.stageId) ?? scope?.stages[0] ?? null; return { phaseId: phase?.id ?? null, scopeId: scope?.id ?? null, stageId: stage?.id ?? null } }
export function selectHierarchyScope(project: PackageProject, selection: HierarchySelection, scopeId: string): HierarchySelection { const phase = project.phases.find((item) => item.id === selection.phaseId) ?? null; const scope = phase?.scopes.find((item) => item.id === scopeId) ?? phase?.scopes[0] ?? null; const stage = scope?.stages.find((item) => item.id === project.current?.stageId) ?? scope?.stages[0] ?? null; return { phaseId: phase?.id ?? null, scopeId: scope?.id ?? null, stageId: stage?.id ?? null } }
export function selectHierarchyStage(project: PackageProject, selection: HierarchySelection, stageId: string): HierarchySelection { const phase = project.phases.find((item) => item.id === selection.phaseId) ?? null; const scope = phase?.scopes.find((item) => item.id === selection.scopeId) ?? null; const stage = scope?.stages.find((item) => item.id === stageId) ?? null; return { phaseId: phase?.id ?? null, scopeId: scope?.id ?? null, stageId: stage?.id ?? null } }
export function resolveHierarchySelection(project: PackageProject, selection: HierarchySelection | null) { const safe = selection && project.phases.some((phase) => phase.id === selection.phaseId) ? selection : defaultHierarchySelection(project); const phase = project.phases.find((item) => item.id === safe.phaseId) ?? null; const scope = phase?.scopes.find((item) => item.id === safe.scopeId) ?? null; const stage = scope?.stages.find((item) => item.id === safe.stageId) ?? null; return { selection: safe, phase, scope, stage } }
export function hierarchyIsExploring(project: PackageProject, selection: HierarchySelection) { return selection.phaseId !== project.current?.phaseId || selection.scopeId !== project.current?.scopeId || selection.stageId !== project.current?.stageId }
export function structuralPhaseModel(project: PackageProject) { return project.phases.map((phase, index) => { const stages = phase.scopes.flatMap((scope) => scope.stages); const complete = stages.filter((stage) => stage.state === 'complete').length; const current = phase.id === project.current?.phaseId; const status = current ? 'current' : stages.length === 0 ? 'definition_pending' : complete === stages.length ? 'complete' : 'pending'; return { id: phase.id, index: index + 1, scopes: phase.scopes.length, stages: stages.length, complete, current, status } }) }
export function collapsedStageCount(stages: PackageStage[], expanded: boolean, selectedStageId: string | null) { if (expanded || stages.length <= 12) return 0; const firstOpen = stages.findIndex((stage) => stage.state !== 'complete'); const count = firstOpen < 0 ? Math.max(0, stages.length - 1) : firstOpen; return stages.slice(0, count).some((stage) => stage.id === selectedStageId) ? 0 : count }

export function gateProgress(stage: PackageStage | null) { const available = Boolean(stage?.gate.available && stage.gate.total > 0); const closed = stage?.gate.closed ?? 0; const total = stage?.gate.total ?? 0; return { available, closed, total, percent: available ? Math.round(closed / total * 100) : null, scale: available ? Math.max(0, Math.min(1, closed / total)) : null } }
export function heroGateEvidence(stage: PackageStage | null) { const value = gateProgress(stage); return { available: value.available, closed: value.closed, total: value.total, scale: value.scale } }
export function hierarchyPlacement(project: PackageProject) { const value = currentHierarchy(project); return { phase: `${value.phaseIndex} / ${value.phaseTotal}`, scope: `${value.scopeIndex} / ${value.scopeTotal}`, stage: `${value.stageIndex} / ${value.stageTotal}` } }
export function deriveScopeState(scope: Scope, currentScopeId: string | undefined): 'complete' | 'active' | 'pending' | 'unknown' { if (!scope.stages.length) return 'unknown'; if (scope.stages.every((stage) => stage.state === 'complete')) return 'complete'; if (scope.id === currentScopeId) return 'active'; if (scope.stages.every((stage) => stage.state === 'unknown')) return 'unknown'; return 'pending' }
export function deriveStageRailState(stage: PackageStage, currentStageId: string | undefined): 'complete' | 'active' | 'pending' | 'unknown' { if (stage.state === 'complete') return 'complete'; if (stage.id === currentStageId) return 'active'; return stage.state === 'unknown' ? 'unknown' : 'pending' }
export function selectLiveBinding(bindings: Binding[]) { return bindings.find((binding) => binding.status === 'active' && binding.freshness === 'fresh') ?? null }
const durationKo = (minutes: number) => { const hours = Math.floor(minutes / 60); const rest = minutes % 60; return hours ? `${hours}시간${rest ? ` ${rest}분` : ''}` : `${rest}분` }
export function timingPresentation(stage: PackageStage, binding: Binding | null, currentStageId: string, now = new Date()) { const boundAt = binding?.boundAt ? Date.parse(binding.boundAt) : NaN; const eligible = Boolean(binding && binding.status === 'active' && binding.freshness === 'fresh' && binding.stageId === currentStageId && Number.isFinite(boundAt) && boundAt <= now.getTime()); if (!eligible || !binding) return { elapsed: { available: false, label: '현재 작업시간', value: '작업시간 측정 근거 없음', basis: null }, eta: { available: false, label: '남은 예상 시간', value: '남은 시간 예상 근거 없음' } }; const elapsedMinutes = Math.max(0, Math.floor((now.getTime() - boundAt) / 60_000)); const expected = Number.isInteger(stage.expectedDurationMinutes) && stage.expectedDurationMinutes! > 0 ? stage.expectedDurationMinutes! : null; return { elapsed: { available: true, label: '현재 역할 연결 후 경과', value: durationKo(elapsedMinutes), basis: `${roleLabel(binding.role)} 연결 시작 ${compactTime(binding.boundAt)}` }, eta: expected === null ? { available: false, label: '남은 예상 시간', value: '남은 시간 예상 근거 없음' } : { available: true, label: '계획 기준 예상', value: durationKo(Math.max(0, expected - elapsedMinutes)) } } }

export function summarizeStage(stage: PackageStage) { const remaining = stage.gate.gates.filter((gate) => !gate.closed); return { closed: stage.gate.closed, total: stage.gate.total, remaining: remaining.slice(0, 3), confirmedPercent: stage.state === 'complete' && stage.gate.total > 0 ? Math.round(stage.gate.closed / stage.gate.total * 100) : null } }
export function stageDetailSemantics(stage: PackageStage, dependencyTitles: string[] = []) { const summary = summarizeStage(stage); const dependency = dependencyTitles.length ? dependencyTitles.join(', ') : '선행 스테이지'; const boundaryByState: Record<string, string> = { locked: `${dependency}가 완료되지 않아 이 스테이지는 잠겨 있습니다.`, blocked: `${dependency} 이후 원본 완료 조건의 ${stateLabelKo(stage.sourceState)} 차단 경계가 해제되어야 진행할 수 있습니다.`, gates_closed_evidence_pending: '체크 항목은 모두 닫혔지만 증거 확정은 아직 대기 중입니다.', queued: '선행 스테이지 완료 후 진입 가능한 대기 상태이며, 아직 완료 증거가 아닙니다.', pending: '원본 묶음의 증거 확정이 대기 중이며 체크 수는 완료 판정이 아닙니다.', active: '현재 스테이지가 진행 중이며 체크 수는 완료 판정이 아닙니다.', unknown: '원본 묶음에 스테이지 상태 근거가 없어 완료 여부를 판단하지 않습니다.' }; const complete = stage.state === 'complete'; const title = stagePresentation(stage.id)[0]; const boundaryCopy = complete ? `${title}의 완료 조건 증거가 원본에서 확정되었습니다.` : boundaryByState[stage.state] ?? `원본 스테이지 상태는 ${stateLabelKo(stage.state)}이며 완료가 아닙니다.`; const checkedCopy = complete ? '연결된 완료 조건의 증거가 모두 확정되었습니다.' : summary.total ? `${summary.closed}/${summary.total} 체크 항목 확인 · ${boundaryCopy}` : `완료 조건 원본이 없어 상태를 판단할 수 없습니다. ${boundaryCopy}`; return { ...summary, countLabel: complete ? '증거 확정 / 전체' : '체크됨 / 전체', boundaryCopy, checkedCopy } }
export function selectedGateCount(stage: PackageStage) { return stage.gate.available && stage.gate.total > 0 ? `${stage.gate.closed}/${stage.gate.total}` : '완료 조건 근거 없음' }
export function detailContentPolicy(exploring: boolean) { return { showTitle: exploring, showPurpose: exploring, showBoundary: exploring, showGateList: exploring } }
export function gateGroupPresentation(name: string, code: string) { const primaryLabel = groupPresentation(name, code); return primaryLabel === '완료 조건 그룹' ? { primaryLabel: null, secondaryCode: null } : { primaryLabel, secondaryCode: code } }
export function meaningfulGateGroups(groups: GateGroup[], available = true) { if (!available) return []; return groups.flatMap((group) => { const presentation = gateGroupPresentation(group.name, group.code); return presentation.primaryLabel ? [{ ...group, ...presentation }] : [] }) }
export function bindingObservationLabel(binding: Binding) { const state = entityStateLabel(binding.status); const freshness = freshnessLabelKo(binding.freshness); return state === freshness ? state : `${state} · ${freshness}` }
export function bindingHeroLabel(binding: Binding) { const state = entityStateLabel(binding.status); if (binding.status === 'stale' && binding.freshness === 'stale') return '관측 오래됨'; if (binding.status === 'unbound') return '연결 없음'; if (binding.status === 'unknown') return binding.freshness === 'stale' ? '근거 없음 · 오래됨' : '근거 없음'; if (binding.status === 'replaced' || binding.freshness === 'replaced') return '교체됨'; const freshness = ({ fresh: '최근', stale: '오래됨', unknown: '관측 미상' } as Record<string, string>)[binding.freshness]; return freshness ? `${state} · ${freshness}` : state }
export function selectProject(projects: PackageProject[], id: string) { return projects.find((project) => project.project.id === id) ?? projects[0] ?? null }
export function selectedStageContext(project: PackageProject, selectedStageId: string | null) { const hierarchy = currentHierarchy(project); const current = hierarchy.stage ? findStage(project, hierarchy.stage.id) : null; const selected = findStage(project, selectedStageId) ?? current ?? findStage(project, project.phases[0]?.scopes[0]?.stages[0]?.id); return { hierarchy, current, selected, exploring: Boolean(current && selected && current.stage.id !== selected.stage.id) } }
export function nextStageOptionIndex(key: string, index: number, total: number) { if (total < 1) return null; if (key === 'ArrowDown') return (index + 1) % total; if (key === 'ArrowUp') return (index - 1 + total) % total; if (key === 'Home') return 0; if (key === 'End') return total - 1; return null }
export function projectHeroModel(project: PackageProject) { const hierarchy = currentHierarchy(project); const next = findStage(project, project.next?.stageId); return { name: project.project.name, outcome: projectOutcomePresentation(project.project.id, project.project.outcome), current: hierarchy.stage ? `${phasePresentation(hierarchy.phase!.id)[0]} → ${scopePresentation(hierarchy.scope!.id)[0]} → ${stagePresentation(hierarchy.stage.id)[0]}` : '현재 위치 근거 없음', next: next ? stagePresentation(next.stage.id)[0] : '다음 단계 근거 없음', freshness: compactTime(project.sourceFreshness?.observedAt ?? project.observedAt) } }
export function nowPresentation(now: PackageProject['now']) { const activity = activityLabelKo(now.activity); const stale = now.status === 'stale' ? entityStateLabel(now.status) : null; return { headline: activity ? `${activity}${stale ? ` · ${stale}` : ''}` : `구현 ${entityStateLabel(now.status)}`, metadata: `${sourceLabelKo(now.source)} · ${compactTime(now.observedAt)} · 세션 활동은 진행률이 아닙니다.` } }
export function githubEvidenceItems(connector: GithubConnector) { const distance = connector.localCandidate.ahead == null || connector.localCandidate.behind == null ? stateLabelKo(connector.localCandidate.sync) : `${connector.localCandidate.ahead}개 앞섬 · ${connector.localCandidate.behind}개 뒤처짐`; return [{ label: '로컬 후보', state: connector.localCandidate.state, value: connector.localCandidate.branch ? `${connector.localCandidate.branch} · ${distance}` : '로컬 근거 없음' }, { label: 'GitHub 게시', state: connector.published.state, value: connector.published.repository ? `${connector.published.repository} · ${connector.published.detail === 'empty_remote' ? '빈 원격 저장소' : connector.published.ref}` : `${connector.defaultBranch ?? '브랜치 근거 없음'} · 저장소 연결 없음` }, { label: '자동 검사', state: connector.checks.state, value: 'GitHub 검사 근거 없음' }, { label: '출시', state: connector.release.state, value: 'GitHub 출시 근거 없음' }] }

export const entityStateLabel = stateLabelKo
export const sourceStateLabel = sourceStateLabelKo
export const axisStateLabel = axisLabelKo
const structureStatusLabel = (value: string) => ({ current: '현재', complete: '완료', pending: '예정', definition_pending: '정의 대기' }[value] ?? '근거 없음')
function StageNode({ state, current }: { state: string; current: boolean }) { return <i className={`${state} ${current ? 'current' : ''}`} aria-hidden="true">{state === 'complete' ? <Check size={11} /> : current ? <Radio size={11} /> : <Circle size={9} />}</i> }
function Axis({ label, value }: { label: string; value: string }) { return <div className="oc-axis"><small>{label}</small><strong>{axisStateLabel(value)}</strong></div> }

export function OutcomeDashboard({ onUnauthorized }: { onUnauthorized: () => void }) {
  const [data, setData] = useState<OutcomeDashboardData | null>(null); const [selectedProjectId, setSelectedProjectId] = useState('outcome'); const [selection, setSelection] = useState<HierarchySelection | null>(null); const [mobileLevel, setMobileLevel] = useState(0); const [stagesExpanded, setStagesExpanded] = useState(false); const [error, setError] = useState<string | null>(null)
  const load = async () => { try { setData(await fetchOutcomeDashboard()); setError(null) } catch (reason) { const message = reason instanceof Error ? reason.message : ''; if (message === 'authentication_required') onUnauthorized(); else setError('대시보드를 읽지 못했습니다.') } }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 10_000); return () => window.clearInterval(timer) }, [])
  const project = useMemo(() => data ? selectProject(data.projects, selectedProjectId) : null, [data, selectedProjectId]); const resolved = project ? resolveHierarchySelection(project, selection) : null
  if (!data || !project || !resolved) return <section className="cn-dashboard cn-loading"><h2>{error ?? 'OUTCOME 원본 묶음을 검증하고 있습니다'}</h2>{error && <button onClick={() => void load()}>다시 확인</button>}</section>
  const current = currentHierarchy(project); if (!current.phase || !current.scope || !current.stage) return <section className="cn-dashboard cn-loading"><h2>현재 위치 원본 근거가 없습니다</h2></section>
  const { phase: selectedPhase, scope: selectedScope, stage: selectedStage } = resolved; const exploring = hierarchyIsExploring(project, resolved.selection); const hero = projectHeroModel(project); const now = nowPresentation(project.now); const liveBinding = selectLiveBinding(project.bindings); const phases = structuralPhaseModel(project)
  const timingBinding = project.bindings.find((binding) => binding.status === 'active' && binding.freshness === 'fresh' && binding.stageId === current.stage!.id) ?? null; const timing = timingPresentation(current.stage, timingBinding, current.stage.id, new Date(data.observedAt))
  const selectedSummary = selectedStage ? stageDetailSemantics(selectedStage, selectedStage.dependsOn.map((id) => stagePresentation(id)[0])) : null; const selectedGroups = selectedStage ? meaningfulGateGroups(selectedStage.gate.groups, selectedStage.gate.available) : []; const selectedProgress = selectedStage?.id === current.stage.id ? gateProgress(selectedStage) : null; const hiddenStageCount = selectedScope ? collapsedStageCount(selectedScope.stages, stagesExpanded, resolved.selection.stageId) : 0; const visibleStages = selectedScope?.stages.slice(hiddenStageCount) ?? []; const github = project.connectors.github
  const switchProject = (id: string) => { setSelectedProjectId(id); setSelection(null); setMobileLevel(0); setStagesExpanded(false) }; const selectPhase = (id: string) => { setSelection(selectHierarchyPhase(project, id)); setMobileLevel(1); setStagesExpanded(false) }; const selectScope = (id: string) => { setSelection(selectHierarchyScope(project, resolved.selection, id)); setMobileLevel(2); setStagesExpanded(false) }; const selectStage = (id: string) => { setSelection(selectHierarchyStage(project, resolved.selection, id)); setMobileLevel(3) }
  const handleColumnKeys = (event: React.KeyboardEvent<HTMLButtonElement>, ids: string[], index: number, choose: (id: string) => void, column: number) => { const nextIndex = nextStageOptionIndex(event.key, index, ids.length); if (nextIndex !== null) { event.preventDefault(); choose(ids[nextIndex]); window.requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-column="${column}"] [role="option"][aria-selected="true"]`)?.focus()); return }; const target = event.key === 'ArrowRight' ? column + 1 : event.key === 'ArrowLeft' ? column - 1 : null; if (target && target >= 1 && target <= 3) { event.preventDefault(); setMobileLevel(target - 1); window.requestAnimationFrame(() => window.requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-column="${target}"] [role="option"][tabindex="0"]`)?.focus())) } }
  const currentBreadcrumb = `${phasePresentation(current.phase.id)[0]} → ${scopePresentation(current.scope.id)[0]} → ${stagePresentation(current.stage.id)[0]}`; const selectedBreadcrumb = [selectedPhase && phasePresentation(selectedPhase.id)[0], selectedScope && scopePresentation(selectedScope.id)[0], selectedStage && stagePresentation(selectedStage.id)[0]].filter(Boolean).join(' → ')

  return <section className="cn-dashboard oc-dashboard" data-project-id={project.project.id} data-current-stage-id={current.stage.id} data-selected-stage-id={selectedStage?.id ?? ''} data-mobile-level={mobileLevel}>
    <header className="oc-topbar"><nav aria-label="프로젝트 전환">{data.projects.map((item) => <button key={item.project.id} aria-label={`${item.project.name} · ${sourceStateLabel(item.status)}`} aria-current={item.project.id === project.project.id ? 'page' : undefined} onClick={() => switchProject(item.project.id)}><i className={item.status} aria-hidden="true" />{item.project.name}<span className="oc-visually-hidden">{sourceStateLabel(item.status)}</span></button>)}</nav></header>
    <section className={`oc-hero ${project.status}`} aria-labelledby="oc-project-title">
      <div className="oc-hero-title"><Layers3 size={22} aria-hidden="true" /><div><h1 id="oc-project-title">{hero.name}</h1><p>{hero.outcome}</p></div></div>
      <div className="oc-hero-meta"><span className={`oc-source ${project.status}`}><strong>{sourceStateLabel(project.status)}</strong><small>원본 관측 {hero.freshness}</small></span><button className="cn-refresh" onClick={() => void load()} aria-label="원본 묶음 새로고침"><RefreshCw size={16} /></button></div>
      <div className="oc-now-summary" data-now-status={project.now.status}><strong>{now.headline}</strong><span>{now.metadata}</span></div>
      <div className="oc-bindings" role="group" aria-label="역할별 세션 관측">{project.bindings.map((binding) => { const live = liveBinding === binding; return <div key={binding.role} className={`oc-role-row ${binding.status}`} data-live={live ? 'true' : 'false'}><strong>{roleLabel(binding.role)}</strong><span>{bindingHeroLabel(binding)}</span>{live && <span className="oc-live-signal" aria-label="실시간 활동"><i aria-hidden="true" /><b>실시간</b></span>}</div> })}</div>
      {project.status !== 'valid' && <div className={`oc-warning ${project.status}`} role="status"><strong>{sourceStateLabel(project.status)}</strong><span>원본 묶음의 참조와 식별자를 다시 확인하세요.</span></div>}
    </section>
    <div className="oc-hierarchy-sticky">
      <div className="oc-structure-band" style={{ '--oc-phase-count': phases.length } as CSSProperties} aria-label="원본 구조 배치" data-structure-signature={phases.map((phase) => `${phase.id}:${phase.complete}/${phase.stages}:${phase.status}`).join('|')}>{phases.map((phase) => <div key={phase.id} className={phase.status} data-phase-id={phase.id}><span><strong>페이즈 {phase.index}</strong><small>{structureStatusLabel(phase.status)}</small></span><b>{phasePresentation(phase.id)[0]}</b><div className="oc-structure-scopes">{project.phases[phase.index - 1].scopes.map((scope) => <span key={scope.id} aria-label={`${scopePresentation(scope.id)[0]} · ${scope.stages.length ? `정의된 스테이지 ${scope.stages.length}개` : '스테이지 정의 대기'}`}>{scope.stages.length ? scope.stages.map((stage) => <i key={stage.id} className={`${stage.state} ${stage.id === project.current?.stageId ? 'current' : ''}`} />) : <i className="definition-pending" />}</span>)}</div></div>)}</div>
      <header className="oc-map-header"><div><h2 id="oc-map-title">결과 지도</h2><p data-current-signature>{currentBreadcrumb}</p>{exploring && <p className="oc-exploration-breadcrumb">탐색 중 · 실제 현재 위치 유지 · {selectedBreadcrumb}</p>}</div><div className="oc-mobile-level"><span>{mobileLevel + 1} / 4</span>{mobileLevel > 0 && <button onClick={() => setMobileLevel((value) => Math.max(0, value - 1))}><ChevronLeft size={16} />이전 단계</button>}</div></header>
    </div>
    <section className="oc-outcome-map" aria-labelledby="oc-map-title"><nav className="oc-mobile-breadcrumb" aria-label="탐색 경로">{selectedPhase && <button onClick={() => setMobileLevel(0)}>페이즈</button>}{selectedScope && <button onClick={() => setMobileLevel(1)}>범위</button>}{selectedStage && <button onClick={() => setMobileLevel(2)}>스테이지</button>}</nav>
      <div className="oc-map-columns">
        <section className="oc-map-column oc-map-phase" data-column="1" data-mobile-active={mobileLevel === 0 ? 'true' : 'false'}><header><h3>페이즈</h3><span>{project.phases.length}개</span></header><div role="listbox" aria-label="프로젝트 페이즈">{project.phases.map((phase, index) => { const selected = phase.id === selectedPhase?.id; const currentItem = phase.id === project.current?.phaseId; const model = phases[index]; return <button key={phase.id} role="option" tabIndex={selected ? 0 : -1} aria-selected={selected} aria-current={currentItem ? 'step' : undefined} data-phase-id={phase.id} data-state={model.status} onKeyDown={(event) => handleColumnKeys(event, project.phases.map((item) => item.id), index, selectPhase, 1)} onClick={() => selectPhase(phase.id)}><StageNode state={model.status === 'complete' ? 'complete' : 'pending'} current={currentItem} /><span><strong>{phasePresentation(phase.id)[0]}</strong><small>{structureStatusLabel(model.status)} · 범위 {phase.scopes.length}개</small></span><ChevronRight size={15} aria-hidden="true" /></button> })}</div></section>
        <section className="oc-map-column oc-map-scope" data-column="2" data-mobile-active={mobileLevel === 1 ? 'true' : 'false'}><header><h3>범위</h3><span>{selectedPhase?.scopes.length ?? 0}개</span></header>{selectedPhase?.scopes.length ? <div role="listbox" aria-label="선택 페이즈 범위">{selectedPhase.scopes.map((scope, index) => { const selected = scope.id === selectedScope?.id; const currentItem = scope.id === project.current?.scopeId; const state = deriveScopeState(scope, project.current?.scopeId); return <button key={scope.id} role="option" tabIndex={selected ? 0 : -1} aria-selected={selected} aria-current={currentItem ? 'step' : undefined} data-scope-id={scope.id} data-state={state} onKeyDown={(event) => handleColumnKeys(event, selectedPhase.scopes.map((item) => item.id), index, selectScope, 2)} onClick={() => selectScope(scope.id)}><StageNode state={state === 'complete' ? 'complete' : 'pending'} current={currentItem} /><span><strong>{scopePresentation(scope.id)[0]}</strong><small>{scope.stages.length ? `스테이지 ${scope.stages.length}개` : '스테이지 정의 대기'}</small></span><ChevronRight size={15} aria-hidden="true" /></button> })}</div> : <p className="oc-empty-state">범위 정의 대기</p>}</section>
        <section className="oc-map-column oc-map-stage" data-column="3" data-mobile-active={mobileLevel === 2 ? 'true' : 'false'}><header><h3>스테이지</h3><span>{selectedScope?.stages.length ?? 0}개</span></header>{hiddenStageCount > 0 && <button className="oc-stage-disclosure" aria-expanded={stagesExpanded} onClick={() => setStagesExpanded(true)}>완료된 스테이지 {hiddenStageCount}개 펼치기</button>}{visibleStages.length ? <div className="oc-map-stage-list" role="listbox" aria-label="선택 범위 스테이지">{visibleStages.map((stage, index) => { const selected = stage.id === selectedStage?.id; const currentItem = stage.id === project.current?.stageId; const sourceIndex = selectedScope!.stages.findIndex((item) => item.id === stage.id); return <button key={stage.id} role="option" tabIndex={selected ? 0 : -1} aria-selected={selected} aria-current={currentItem ? 'step' : undefined} data-stage-id={stage.id} data-state={stage.state} onKeyDown={(event) => handleColumnKeys(event, visibleStages.map((item) => item.id), index, selectStage, 3)} onClick={() => selectStage(stage.id)}><StageNode state={stage.state} current={currentItem} /><span><strong>{stagePresentation(stage.id)[0]}</strong><small>{entityStateLabel(stage.state)} · {sourceIndex + 1}/{selectedScope!.stages.length}</small></span><ChevronRight size={15} aria-hidden="true" /></button> })}</div> : <p className="oc-empty-state">스테이지 정의 대기 · 완료 조건을 추론하지 않습니다.</p>}</section>
        <section className="oc-gate-inspector" data-column="4" data-mobile-active={mobileLevel === 3 ? 'true' : 'false'} data-stage-state={selectedStage?.state ?? 'unknown'} data-gate-available={selectedStage?.gate.available ? 'true' : 'false'} data-gate-closed={selectedStage?.gate.closed ?? 0} data-gate-total={selectedStage?.gate.total ?? 0} aria-label="선택 스테이지 완료 조건"><header><small>완료 조건 · 스테이지 수용 기준</small>{selectedStage ? <><h3>{stagePresentation(selectedStage.id)[0]}</h3><p>{stagePresentation(selectedStage.id)[1]}</p></> : <><h3>스테이지 정의 대기</h3><p>선택한 범위에 스테이지와 완료 조건이 아직 정의되지 않았습니다.</p></>}</header>{selectedStage && selectedSummary && <><div className="oc-gate-count"><span><small>확인된 항목 / 전체</small><strong>{selectedGateCount(selectedStage)}</strong></span><em>{entityStateLabel(selectedStage.state)}</em></div>{selectedProgress?.available && <span className="oc-gate-gauge" role="img" aria-label={`현재 스테이지 완료 조건 ${selectedProgress.closed}/${selectedProgress.total}`}><i style={{ transform: `scaleX(${selectedProgress.scale})` }} /></span>}<p className="oc-detail-boundary">{selectedSummary.boundaryCopy}</p><section className="oc-inspector-gates"><h4>남은 완료 조건</h4>{selectedStage.gate.gates.some((gate) => !gate.closed) ? <ol>{selectedStage.gate.gates.filter((gate) => !gate.closed).map((gate) => <li key={gate.id}><b>{gate.id}</b><span>{gatePresentation(selectedStage.id, gate.id)}</span></li>)}</ol> : <p>{selectedSummary.checkedCopy}</p>}</section>{selectedGroups.length > 0 && <section data-source-groups><h4>그룹별 확인</h4><div className="oc-groups">{selectedGroups.map((group) => <article key={group.code} data-generic="false"><span><strong>{group.primaryLabel}</strong><small>코드 {group.secondaryCode}</small></span><b>{group.closed}/{group.total}</b></article>)}</div></section>}</>}</section>
      </div>
    </section>
    <details className="oc-technical"><summary><span>기술 증거</span><small>빌드·역할 연결·GitHub·근거 축</small></summary><div className="oc-technical-content"><div className="oc-build" aria-label="제공 중인 고정 빌드"><small>기술 증거 · 프로젝트 식별자 {project.project.id} · {data.build.repository}/{data.build.ref}</small><strong>커밋 {data.build.commit ?? '근거 없음'} · 트리 {data.build.tree ?? '근거 없음'}</strong><span>에셋 {data.build.asset ?? '근거 없음'} · 실시간 현재 작업은 빌드에 고정되지 않음</span></div><section className="oc-timing-evidence" aria-label="시간 근거"><div><small>{timing.elapsed.label}</small><strong>{timing.elapsed.value}</strong>{timing.elapsed.basis && <span>{timing.elapsed.basis}</span>}</div><div><small>{timing.eta.label}</small><strong>{timing.eta.value}</strong></div></section><section className="oc-binding-evidence" aria-label="역할 연결 기술 증거"><h3>역할 연결 근거</h3>{project.bindings.map((binding) => <div key={binding.role}><strong>{roleLabel(binding.role)}</strong><span>{binding.stageId ?? '스테이지 연결 없음'} · 이력 {binding.historyCount} · 관측 {compactTime(binding.observedAt)}</span></div>)}</section><section className="oc-github" aria-label="GitHub 전달 근거 연결"><header><div><small>선택 연결 근거 · GitHub</small><strong>{github.adopted ? 'GitHub 연결 채택' : 'GitHub 연결 미채택'}</strong></div><span className={github.state}>{entityStateLabel(github.state)}</span></header><div>{githubEvidenceItems(github).map((item) => <article key={item.label} className={item.state}><small>{item.label}</small><strong>{item.value}</strong><span>{entityStateLabel(item.state)}</span></article>)}</div><p>완료 판정 권한 없음 · GitHub 활동은 완료 조건 충족이나 Cherry 승인이 아닙니다.</p></section>{selectedStage && <div className="oc-axes" aria-label="선택 스테이지 근거 축"><Axis label="구현" value={selectedStage.axes.implementation} /><Axis label="테스트" value={selectedStage.axes.test} /><Axis label="증거 확정" value={selectedStage.axes.evidence} /><Axis label="변화 관측" value={project.now.status} /></div>}</div></details>
  </section>
}
