import { describe, expect, it } from 'vitest'
import { entityStateLabel, findStage, githubEvidenceItems, selectProject, sourceStateLabel, summarizeStage, type GithubConnector, type PackageProject, type PackageStage } from './OutcomeDashboard'

const stage = (overrides: Partial<PackageStage> = {}): PackageStage => ({ id: 'stage-one', title: 'Stage One', purpose: 'Verify the result', dependsOn: [], gatePurpose: 'Stage One acceptance checklist', sourceState: 'present', state: 'active', gate: { gates: [{ id: 'G1', title: 'closed', closed: true, groupCode: 'G' }, { id: 'G2', title: 'remaining', closed: false, groupCode: 'G' }], groups: [{ code: 'G', name: '증거', closed: 1, total: 2 }], total: 2, closed: 1, available: true, sourceRef: 'GATES.md' }, axes: { implementation: 'active', test: 'pending', evidence: 'pending', independentQa: 'not_started', cherryAcceptance: 'pending', release: 'not_started' }, ...overrides })
const github = (overrides: Partial<GithubConnector> = {}): GithubConnector => ({ adopted: true, required: false, state: 'connected', repository: 'owner/repo', remoteName: 'origin', defaultBranch: 'main', completionAuthority: false, localCandidate: { state: 'available', branch: 'main', ahead: 15, behind: 0, sync: 'ahead' }, published: { state: 'connected', repository: 'owner/repo', ref: 'origin/main', detail: 'published' }, checks: { state: 'unknown' }, release: { state: 'unknown' }, ...overrides })
const project = (id: string, title: string): PackageProject => ({ status: 'valid', errors: [], observedAt: null, project: { id, name: title, outcome: `${title} outcome`, acceptanceAuthority: 'Cherry' }, connectors: { github: github() }, phases: [{ id: `${id}-phase`, title: 'Phase', purpose: 'Phase purpose', completion: null, scopes: [{ id: `${id}-scope`, title: 'Scope', purpose: 'Scope purpose', stages: [stage({ id: `${id}-stage` })] }] }], current: { phaseId: `${id}-phase`, scopeId: `${id}-scope`, stageId: `${id}-stage` }, next: null, bindings: [], now: { status: 'unbound', activity: null, observedAt: null, source: 'runtime_registry' }, progress: { available: false, reason: 'no_cross_stage_aggregate' } })

describe('OUTCOME Package dashboard', () => {
  it('project switch keeps Package truth isolated', () => { const projects = [project('cherry-note', 'Cherry Note'), project('outcome', 'OUTCOME')]; expect(selectProject(projects, 'outcome')?.project.outcome).toBe('OUTCOME outcome'); expect(selectProject(projects, 'cherry-note')?.project.outcome).toBe('Cherry Note outcome') })
  it('purpose funnel resolves Phase Scope and Stage from one project', () => { const value = project('outcome', 'OUTCOME'); const found = findStage(value, 'outcome-stage'); expect([found?.phase.purpose, found?.scope.purpose, found?.stage.purpose]).toEqual(['Phase purpose', 'Scope purpose', 'Verify the result']) })
  it('stage summary reports closed total and remaining Gate evidence', () => { expect(summarizeStage(stage())).toEqual({ closed: 1, total: 2, remaining: [{ id: 'G2', title: 'remaining', closed: false, groupCode: 'G' }], confirmedPercent: 50 }) })
  it('stage summary makes no percentage without Gate evidence', () => { expect(summarizeStage(stage({ gate: { gates: [], groups: [], total: 0, closed: 0, available: false, sourceRef: null } })).confirmedPercent).toBeNull() })
  it('evidence layers remain separate from NOW activity', () => { const value = project('outcome', 'OUTCOME'); value.now.activity = 'many edits'; expect(value.progress.available).toBe(false); expect(findStage(value, value.current?.stageId)?.stage.axes.evidence).toBe('pending') })
  it('GitHub evidence keeps local published checks and release separate', () => { const items = githubEvidenceItems(github()); expect(items.map((item) => item.label)).toEqual(['LOCAL CANDIDATE', 'GITHUB PUBLISHED', 'CHECKS', 'RELEASE']); expect(items[0].value).toContain('15 ahead'); expect(items[1].value).toContain('origin/main'); expect(items[2].state).toBe('unknown'); expect(items[3].state).toBe('unknown') })
  it('GitHub evidence shows connected empty remote as not published', () => { const items = githubEvidenceItems(github({ repository: 'dltmddnr3/outcome', published: { state: 'not_published', repository: 'dltmddnr3/outcome', ref: 'origin/main', detail: 'empty_remote' } })); expect(items[1]).toEqual({ label: 'GITHUB PUBLISHED', state: 'not_published', value: 'dltmddnr3/outcome · empty remote' }) })
  it('accessibility correction keeps source and entity vocabulary separate', () => { expect(sourceStateLabel('unknown')).toBe('PACKAGE SOURCE UNKNOWN'); expect(entityStateLabel('unknown')).toBe('근거 없음'); expect(entityStateLabel('stale')).toBe('binding 오래됨'); expect(entityStateLabel('queued')).toBe('진입 대기'); expect(entityStateLabel('locked')).toBe('선행 Gate 잠김') })
})
