import { useEffect, useRef, useState, type CSSProperties } from 'react'
import { Archive, Check, ChevronLeft, ChevronRight, Circle, Layers3, Menu, MoreHorizontal, Plug, Plus, Radio, RefreshCw, Search, UserRound, X } from 'lucide-react'
import { fetchOutcomeDashboard, type PrivateProjectProjection } from '../lib/api'
import { CurrentProjection } from './CurrentProjection'
import { PlannerConversation } from './PlannerConversation'
import { activityLabelKo, axisLabelKo, freshnessLabelKo, gatePresentation, groupPresentation, phasePresentation, projectOutcomePresentation, roleLabel, scopePresentation, sourceLabelKo, sourceStateLabelKo, stagePresentation, stateLabelKo } from './outcomeKorean'

type SourceState = 'valid' | 'stale' | 'unknown' | 'conflict'
export type BindingHistory = { action: string; before_version: number; after_version: number; occurred_at: string; reason_class: string; stage_id?: string | null }
export type Binding = { role: string; status: string; activity: string | null; boundAt: string | null; observedAt: string | null; freshness: string; bindingVersion?: number; historyCount: number; phaseId?: string | null; scopeId?: string | null; stageId?: string | null; rotating?: boolean; hasPredecessor?: boolean; history?: BindingHistory[] }
type Gate = { id: string; title: string; closed: boolean; groupCode: string }
type GateGroup = { code: string; name: string; total: number; closed: number }
export type PackageStage = { id: string; title: string; purpose: string; dependsOn: string[]; expectedDurationMinutes?: number | null; gatePurpose: string; sourceState: string; state: string; gate: { gates: Gate[]; groups: GateGroup[]; total: number; closed: number; available: boolean; sourceRef: string | null }; axes: { implementation: string; test: string; evidence: string; independentQa: string; cherryAcceptance: string; release: string } }
export type Scope = { id: string; title: string; purpose: string; stages: PackageStage[] }
export type Phase = { id: string; title: string; purpose: string; completion: string | null; scopes: Scope[] }
export type GithubConnector = { adopted: boolean; required: boolean; state: string; repository: string | null; remoteName: string | null; defaultBranch: string | null; completionAuthority: false; localCandidate: { state: string; branch: string | null; ahead: number | null; behind: number | null; sync: string }; published: { state: string; repository: string | null; ref: string | null; detail: string }; checks: { state: string }; release: { state: string } }
export type PackageProject = { status: SourceState; errors: string[]; observedAt: string | null; sourceFreshness?: { state: string; observedAt: string | null }; project: { id: string; name: string; outcome: string; acceptanceAuthority: string }; connectors: { github: GithubConnector }; phases: Phase[]; current: { phaseId: string; scopeId: string; stageId: string } | null; next: { phaseId: string; scopeId: string; stageId: string } | null; bindings: Binding[]; now: { status: string; activity: string | null; observedAt: string | null; source: string }; progress: { available: false; reason: string } }
export type DeploymentSnapshot = { boundary: 'deployment_snapshot'; capturedAt: string; source: 'sanitized_public_projection'; liveSessionRelay: false; refreshBehavior: 'new_deployment_required' }
export type OutcomeDashboardData = { schemaVersion: 2; observedAt: string; snapshot?: DeploymentSnapshot; build: { repository: string; ref: string; commit: string | null; tree: string | null; asset: string | null; runtimeNowPinned: false }; projects: PackageProject[] }
export type HierarchySelection = { phaseId: string | null; scopeId: string | null; stageId: string | null }
export const mobileHierarchyLevels = ['페이즈', '범위', '스테이지'] as const
export const mobileWorkspaceTabs = ['지도', '대화', '승인'] as const
export const desktopConversationBreakpoint = 1100
export const workspaceManagementItems = [
  { id: 'archive', label: '보관함', disabled: true },
  { id: 'connections', label: '연결 관리', disabled: true },
] as const

const compactTime = (value: string | null) => value ? new Intl.DateTimeFormat('ko-KR', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '근거 없음'
export function findStage(project: PackageProject, stageId: string | null | undefined) { for (const phase of project.phases) for (const scope of phase.scopes) for (const stage of scope.stages) if (stage.id === stageId) return { phase, scope, stage }; return null }
export function currentHierarchy(project: PackageProject) { const phaseIndex = project.phases.findIndex((phase) => phase.id === project.current?.phaseId); const phase = phaseIndex >= 0 ? project.phases[phaseIndex] : null; const scopeIndex = phase?.scopes.findIndex((scope) => scope.id === project.current?.scopeId) ?? -1; const scope = phase && scopeIndex >= 0 ? phase.scopes[scopeIndex] : null; const stageIndex = scope?.stages.findIndex((stage) => stage.id === project.current?.stageId) ?? -1; const stage = scope && stageIndex >= 0 ? scope.stages[stageIndex] : null; return { phase, scope, stage, phaseIndex: phaseIndex + 1, phaseTotal: project.phases.length, scopeIndex: scopeIndex + 1, scopeTotal: phase?.scopes.length ?? 0, stageIndex: stageIndex + 1, stageTotal: scope?.stages.length ?? 0 } }

export function defaultHierarchySelection(project: PackageProject): HierarchySelection { const phase = project.phases.find((item) => item.id === project.current?.phaseId) ?? project.phases[0] ?? null; const scope = phase?.scopes.find((item) => item.id === project.current?.scopeId) ?? phase?.scopes[0] ?? null; const stage = scope?.stages.find((item) => item.id === project.current?.stageId) ?? scope?.stages[0] ?? null; return { phaseId: phase?.id ?? null, scopeId: scope?.id ?? null, stageId: stage?.id ?? null } }
export function selectHierarchyPhase(project: PackageProject, phaseId: string): HierarchySelection { const phase = project.phases.find((item) => item.id === phaseId) ?? project.phases[0] ?? null; const scope = phase?.scopes.find((item) => item.id === project.current?.scopeId) ?? phase?.scopes[0] ?? null; const stage = scope?.stages.find((item) => item.id === project.current?.stageId) ?? scope?.stages[0] ?? null; return { phaseId: phase?.id ?? null, scopeId: scope?.id ?? null, stageId: stage?.id ?? null } }
export function selectHierarchyScope(project: PackageProject, selection: HierarchySelection, scopeId: string): HierarchySelection { const phase = project.phases.find((item) => item.id === selection.phaseId) ?? null; const scope = phase?.scopes.find((item) => item.id === scopeId) ?? phase?.scopes[0] ?? null; const stage = scope?.stages.find((item) => item.id === project.current?.stageId) ?? scope?.stages[0] ?? null; return { phaseId: phase?.id ?? null, scopeId: scope?.id ?? null, stageId: stage?.id ?? null } }
export function selectHierarchyStage(project: PackageProject, selection: HierarchySelection, stageId: string): HierarchySelection { const phase = project.phases.find((item) => item.id === selection.phaseId) ?? null; const scope = phase?.scopes.find((item) => item.id === selection.scopeId) ?? null; const stage = scope?.stages.find((item) => item.id === stageId) ?? null; return { phaseId: phase?.id ?? null, scopeId: scope?.id ?? null, stageId: stage?.id ?? null } }
export function resolveHierarchySelection(project: PackageProject, selection: HierarchySelection | null) { const safe = selection && project.phases.some((phase) => phase.id === selection.phaseId) ? selection : defaultHierarchySelection(project); const phase = project.phases.find((item) => item.id === safe.phaseId) ?? null; const scope = phase?.scopes.find((item) => item.id === safe.scopeId) ?? null; const stage = scope?.stages.find((item) => item.id === safe.stageId) ?? null; return { selection: safe, phase, scope, stage } }
export function hierarchyIsExploring(project: PackageProject, selection: HierarchySelection) { return selection.phaseId !== project.current?.phaseId || selection.scopeId !== project.current?.scopeId || selection.stageId !== project.current?.stageId }
export function structuralPhaseModel(project: PackageProject) { return project.phases.map((phase, index) => { const stages = phase.scopes.flatMap((scope) => scope.stages); const complete = stages.filter((stage) => stage.state === 'complete').length; const current = phase.id === project.current?.phaseId; const hasUndefinedScope = phase.scopes.length === 0 || phase.scopes.some((scope) => scope.stages.length === 0); const status = stages.length === 0 ? 'definition_pending' : !hasUndefinedScope && complete === stages.length ? 'complete' : complete > 0 ? 'partial' : current ? 'current' : 'pending'; return { id: phase.id, index: index + 1, scopes: phase.scopes.length, stages: stages.length, complete, current, status } }) }
export function collapsedStageCount(stages: PackageStage[], expanded: boolean, selectedStageId: string | null) { if (expanded || stages.length <= 12) return 0; const firstOpen = stages.findIndex((stage) => stage.state !== 'complete'); const count = firstOpen < 0 ? Math.max(0, stages.length - 1) : firstOpen; return stages.slice(0, count).some((stage) => stage.id === selectedStageId) ? 0 : count }

export function gateProgress(stage: PackageStage | null) { const available = Boolean(stage?.gate.available && stage.gate.total > 0); const closed = stage?.gate.closed ?? 0; const total = stage?.gate.total ?? 0; return { available, closed, total, percent: available ? Math.round(closed / total * 100) : null, scale: available ? Math.max(0, Math.min(1, closed / total)) : null } }
export function heroGateEvidence(stage: PackageStage | null) { const value = gateProgress(stage); return { available: value.available, closed: value.closed, total: value.total, scale: value.scale } }
export function hierarchyPlacement(project: PackageProject) { const value = currentHierarchy(project); return { phase: `${value.phaseIndex} / ${value.phaseTotal}`, scope: `${value.scopeIndex} / ${value.scopeTotal}`, stage: `${value.stageIndex} / ${value.stageTotal}` } }
export function deriveScopeState(scope: Scope, currentScopeId: string | undefined): 'complete' | 'active' | 'pending' | 'unknown' { if (!scope.stages.length) return 'unknown'; if (scope.stages.every((stage) => stage.state === 'complete')) return 'complete'; if (scope.id === currentScopeId) return 'active'; if (scope.stages.every((stage) => stage.state === 'unknown')) return 'unknown'; return 'pending' }
export function deriveStageRailState(stage: PackageStage, currentStageId: string | undefined): 'complete' | 'active' | 'pending' | 'unknown' { if (stage.state === 'complete') return 'complete'; if (stage.id === currentStageId) return 'active'; return stage.state === 'unknown' ? 'unknown' : 'pending' }
export function selectLiveBinding(bindings: Binding[]) { return bindings.find((binding) => binding.status === 'active' && binding.freshness === 'fresh') ?? null }
export function snapshotPresentation(snapshot: DeploymentSnapshot | undefined) { return snapshot?.boundary === 'deployment_snapshot' ? { label: '배포 스냅샷', detail: snapshot.liveSessionRelay ? '실시간 세션 연결됨' : '실시간 세션 연결 대기 · 새 배포 시 갱신', sourceLabel: '패키지 구조 정상', timePrefix: '스냅샷 생성', refreshLabel: '배포 스냅샷 다시 불러오기' } : null }
const durationKo = (minutes: number) => { const hours = Math.floor(minutes / 60); const rest = minutes % 60; return hours ? `${hours}시간${rest ? ` ${rest}분` : ''}` : `${rest}분` }
export function timingPresentation(stage: PackageStage, binding: Binding | null, currentStageId: string, now = new Date()) { const boundAt = binding?.boundAt ? Date.parse(binding.boundAt) : NaN; const eligible = Boolean(binding && binding.status === 'active' && binding.freshness === 'fresh' && binding.stageId === currentStageId && Number.isFinite(boundAt) && boundAt <= now.getTime()); if (!eligible || !binding) return { elapsed: { available: false, label: '현재 작업시간', value: '작업시간 측정 근거 없음', basis: null }, eta: { available: false, label: '남은 예상 시간', value: '남은 시간 예상 근거 없음' } }; const elapsedMinutes = Math.max(0, Math.floor((now.getTime() - boundAt) / 60_000)); const expected = Number.isInteger(stage.expectedDurationMinutes) && stage.expectedDurationMinutes! > 0 ? stage.expectedDurationMinutes! : null; return { elapsed: { available: true, label: '현재 역할 연결 후 경과', value: durationKo(elapsedMinutes), basis: `${roleLabel(binding.role)} 연결 시작 ${compactTime(binding.boundAt)}` }, eta: expected === null ? { available: false, label: '남은 예상 시간', value: '남은 시간 예상 근거 없음' } : { available: true, label: '계획 기준 예상', value: durationKo(Math.max(0, expected - elapsedMinutes)) } } }

export function summarizeStage(stage: PackageStage) { const remaining = stage.gate.gates.filter((gate) => !gate.closed); return { closed: stage.gate.closed, total: stage.gate.total, remaining: remaining.slice(0, 3), confirmedPercent: stage.state === 'complete' && stage.gate.total > 0 ? Math.round(stage.gate.closed / stage.gate.total * 100) : null } }
export function stageDetailSemantics(stage: PackageStage, dependencyTitles: string[] = []) { const summary = summarizeStage(stage); const dependency = dependencyTitles.length ? dependencyTitles.join(', ') : '선행 스테이지'; const boundaryByState: Record<string, string> = { locked: `${dependency}가 완료되지 않아 이 스테이지는 잠겨 있습니다.`, blocked: `${dependency} 이후 원본 완료 조건의 ${stateLabelKo(stage.sourceState)} 차단 경계가 해제되어야 진행할 수 있습니다.`, gates_closed_evidence_pending: '체크 항목은 모두 닫혔지만 증거 확정은 아직 대기 중입니다.', queued: '선행 스테이지 완료 후 진입 가능한 대기 상태이며, 아직 완료 증거가 아닙니다.', pending: '원본 묶음의 증거 확정이 대기 중이며 체크 수는 완료 판정이 아닙니다.', active: '현재 스테이지가 진행 중이며 체크 수는 완료 판정이 아닙니다.', unknown: '원본 묶음에 스테이지 상태 근거가 없어 완료 여부를 판단하지 않습니다.' }; const complete = stage.state === 'complete'; const title = stagePresentation(stage.id, stage.title, stage.purpose)[0]; const boundaryCopy = complete ? `${title}의 완료 조건 증거가 원본에서 확정되었습니다.` : boundaryByState[stage.state] ?? `원본 스테이지 상태는 ${stateLabelKo(stage.state)}이며 완료가 아닙니다.`; const checkedCopy = complete ? '연결된 완료 조건의 증거가 모두 확정되었습니다.' : summary.total ? `${summary.closed}/${summary.total} 체크 항목 확인 · ${boundaryCopy}` : `완료 조건 원본이 없어 상태를 판단할 수 없습니다. ${boundaryCopy}`; return { ...summary, countLabel: complete ? '증거 확정 / 전체' : '체크됨 / 전체', boundaryCopy, checkedCopy } }
export function selectedGateCount(stage: PackageStage) { return stage.gate.available && stage.gate.total > 0 ? `${stage.gate.closed}/${stage.gate.total}` : '완료 조건 근거 없음' }
export function detailContentPolicy(exploring: boolean) { return { showTitle: exploring, showPurpose: exploring, showBoundary: exploring, showGateList: exploring } }
export function gateGroupPresentation(name: string, code: string) { const primaryLabel = groupPresentation(name, code); return primaryLabel === '완료 조건 그룹' ? { primaryLabel: null, secondaryCode: null } : { primaryLabel, secondaryCode: code } }
export function meaningfulGateGroups(groups: GateGroup[], available = true) { if (!available) return []; return groups.flatMap((group) => { const presentation = gateGroupPresentation(group.name, group.code); return presentation.primaryLabel ? [{ ...group, ...presentation }] : [] }) }
export function bindingObservationLabel(binding: Binding) { const state = entityStateLabel(binding.status); const freshness = freshnessLabelKo(binding.freshness); return state === freshness ? state : `${state} · ${freshness}` }
export function bindingHeroLabel(binding: Binding) { const state = entityStateLabel(binding.status); if (binding.status === 'stale' && binding.freshness === 'stale') return '관측 오래됨'; if (binding.status === 'unbound') return '연결 없음'; if (binding.status === 'unknown') return binding.freshness === 'stale' ? '근거 없음 · 오래됨' : '근거 없음'; if (binding.status === 'replaced' || binding.freshness === 'replaced') return '교체됨'; const freshness = ({ fresh: '최근', stale: '오래됨', unknown: '관측 미상' } as Record<string, string>)[binding.freshness]; return freshness ? `${state} · ${freshness}` : state }
export function selectProject(projects: PackageProject[], id: string) { return projects.find((project) => project.project.id === id) ?? projects[0] ?? null }
export function selectedStageContext(project: PackageProject, selectedStageId: string | null) { const hierarchy = currentHierarchy(project); const current = hierarchy.stage ? findStage(project, hierarchy.stage.id) : null; const selected = findStage(project, selectedStageId) ?? current ?? findStage(project, project.phases[0]?.scopes[0]?.stages[0]?.id); return { hierarchy, current, selected, exploring: Boolean(current && selected && current.stage.id !== selected.stage.id) } }
export function nextStageOptionIndex(key: string, index: number, total: number) { if (total < 1) return null; if (key === 'ArrowDown') return (index + 1) % total; if (key === 'ArrowUp') return (index - 1 + total) % total; if (key === 'Home') return 0; if (key === 'End') return total - 1; return null }
export function projectHeroModel(project: PackageProject) { const hierarchy = currentHierarchy(project); const next = findStage(project, project.next?.stageId); return { name: project.project.name, outcome: projectOutcomePresentation(project.project.id, project.project.outcome), current: hierarchy.stage ? `${phasePresentation(hierarchy.phase!.id, hierarchy.phase!.title, hierarchy.phase!.purpose)[0]} → ${scopePresentation(hierarchy.scope!.id, hierarchy.scope!.title, hierarchy.scope!.purpose)[0]} → ${stagePresentation(hierarchy.stage.id, hierarchy.stage.title, hierarchy.stage.purpose)[0]}` : '현재 위치 근거 없음', next: next ? stagePresentation(next.stage.id, next.stage.title, next.stage.purpose)[0] : '다음 단계 근거 없음', freshness: compactTime(project.sourceFreshness?.observedAt ?? project.observedAt) } }
export function nowPresentation(now: PackageProject['now']) { const activity = activityLabelKo(now.activity); const stale = now.status === 'stale' ? entityStateLabel(now.status) : null; return { headline: activity ? `${activity}${stale ? ` · ${stale}` : ''}` : `구현 ${entityStateLabel(now.status)}`, metadata: `${sourceLabelKo(now.source)} · ${compactTime(now.observedAt)} · 세션 활동은 진행률이 아닙니다.` } }
export function githubEvidenceItems(connector: GithubConnector) { const distance = connector.localCandidate.ahead == null || connector.localCandidate.behind == null ? stateLabelKo(connector.localCandidate.sync) : `${connector.localCandidate.ahead}개 앞섬 · ${connector.localCandidate.behind}개 뒤처짐`; return [{ label: '로컬 후보', state: connector.localCandidate.state, value: connector.localCandidate.branch ? `${connector.localCandidate.branch} · ${distance}` : '로컬 근거 없음' }, { label: 'GitHub 게시', state: connector.published.state, value: connector.published.repository ? `${connector.published.repository} · ${connector.published.detail === 'empty_remote' ? '빈 원격 저장소' : connector.published.ref}` : `${connector.defaultBranch ?? '브랜치 근거 없음'} · 저장소 연결 없음` }, { label: '자동 검사', state: connector.checks.state, value: 'GitHub 검사 근거 없음' }, { label: '출시', state: connector.release.state, value: 'GitHub 출시 근거 없음' }] }

export const entityStateLabel = stateLabelKo
export const sourceStateLabel = sourceStateLabelKo
export const axisStateLabel = axisLabelKo
export const structureStatusLabel = (value: string) => ({ current: '현재', complete: '완료', partial: '일부 완료', pending: '예정', definition_pending: '정의 대기' }[value] ?? '근거 없음')
function StageNode({ state, current }: { state: string; current: boolean }) { return <i className={`${state} ${current ? 'current' : ''}`} aria-hidden="true">{state === 'complete' ? <Check size={11} /> : current ? <Radio size={11} /> : <Circle size={9} />}</i> }
function Axis({ label, value }: { label: string; value: string }) { return <div className="oc-axis"><small>{label}</small><strong>{axisStateLabel(value)}</strong></div> }

export function OutcomeDashboard({ onUnauthorized, initialData, onLogout, privateProjects }: { onUnauthorized: () => void; initialData?: OutcomeDashboardData; onLogout?: () => Promise<void>; privateProjects?: PrivateProjectProjection[] }) {
  const [data, setData] = useState<OutcomeDashboardData | null>(initialData ?? null); const [selectedProjectId, setSelectedProjectId] = useState('outcome'); const [selection, setSelection] = useState<HierarchySelection | null>(null); const [mobileLevel, setMobileLevel] = useState(0); const [workspaceTab, setWorkspaceTab] = useState<(typeof mobileWorkspaceTabs)[number]>('지도'); const [stagesExpanded, setStagesExpanded] = useState(false); const [error, setError] = useState<string | null>(null)
  const [navigationOpen, setNavigationOpen] = useState(false); const [projectQuery, setProjectQuery] = useState(''); const menuButtonRef = useRef<HTMLButtonElement>(null); const navigationRef = useRef<HTMLElement>(null); const contentRef = useRef<HTMLElement>(null)
  const load = async () => { if (initialData) { setData(initialData); setError(null); return }; try { setData(await fetchOutcomeDashboard()); setError(null) } catch (reason) { const message = reason instanceof Error ? reason.message : ''; if (message === 'authentication_required') onUnauthorized(); else setError('대시보드를 읽지 못했습니다.') } }
  useEffect(() => { if (initialData) { setData(initialData); return }; void load(); const timer = window.setInterval(() => void load(), 10_000); return () => window.clearInterval(timer) }, [initialData])
  useEffect(() => {
    if (!navigationOpen) return
    const content = contentRef.current; const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'; if (content) content.inert = true
    const focusable = () => Array.from(navigationRef.current?.querySelectorAll<HTMLElement>('a[href], button:not([disabled])') ?? []).filter((item) => item.tabIndex >= 0)
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { event.preventDefault(); setNavigationOpen(false); window.requestAnimationFrame(() => menuButtonRef.current?.focus()); return }
      if (event.key !== 'Tab') return
      const items = focusable(); if (!items.length) return
      const first = items[0]; const last = items[items.length - 1]
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() }
    }
    document.addEventListener('keydown', onKeyDown); window.requestAnimationFrame(() => navigationRef.current?.querySelector<HTMLElement>('.oc-nav-close')?.focus())
    return () => { document.body.style.overflow = previousOverflow; if (content) content.inert = false; document.removeEventListener('keydown', onKeyDown) }
  }, [navigationOpen])
  const dashboardProjects = data ? privateProjects?.length ? data.projects.filter((item) => privateProjects.some((privateProject) => privateProject.project.id === item.project.id)) : data.projects : []
  const project = data ? selectProject(dashboardProjects, selectedProjectId) : null
  const privateOnlyProject = privateProjects?.find((item) => item.project.id === selectedProjectId) ?? privateProjects?.[0]
  const privateDashboardMismatch = Boolean(data && privateProjects?.some((privateProject) => !dashboardProjects.some((item) => item.project.id === privateProject.project.id)))
  if ((!data || privateDashboardMismatch) && privateOnlyProject?.modelV2) {
    const closePrivateNavigation = (restoreFocus = false) => { setNavigationOpen(false); if (restoreFocus) window.requestAnimationFrame(() => menuButtonRef.current?.focus()) }
    const switchPrivateProject = (id: string) => { setSelectedProjectId(id); closePrivateNavigation() }
    const normalizedPrivateQuery = projectQuery.trim().toLocaleLowerCase('ko-KR')
    const privateSidebarProjects = normalizedPrivateQuery ? privateProjects!.filter((item) => item.project.name.toLocaleLowerCase('ko-KR').includes(normalizedPrivateQuery)) : privateProjects!
    return <section className="cn-dashboard oc-dashboard" data-project-id={privateOnlyProject.project.id} data-compatibility-available="false">
      <a className="oc-skip-link" href="#oc-main-content">본문으로 건너뛰기</a>
      {navigationOpen && <button className="oc-nav-backdrop" aria-label="탐색 닫기" tabIndex={-1} onClick={() => closePrivateNavigation(true)} />}
      <aside ref={navigationRef} className="oc-global-nav" data-open={navigationOpen ? 'true' : 'false'} aria-label="OUTCOME 전역 탐색" role={navigationOpen ? 'dialog' : undefined} aria-modal={navigationOpen ? true : undefined}>
        <header><span className="oc-nav-brand"><Layers3 size={20} aria-hidden="true" /><strong>OUTCOME</strong></span><button className="oc-nav-close" aria-label="탐색 닫기" onClick={() => closePrivateNavigation(true)}><X size={20} aria-hidden="true" /></button></header>
        <div className="oc-nav-workspace"><button className="oc-new-project" type="button" disabled aria-label="새 프로젝트 · 준비 중"><Plus size={18} aria-hidden="true" /><span>새 프로젝트</span><small>준비 중</small></button>
          <label className="oc-project-search"><Search size={18} aria-hidden="true" /><span className="oc-visually-hidden">프로젝트 검색</span><input type="search" value={projectQuery} onChange={(event) => setProjectQuery(event.target.value)} placeholder="프로젝트 검색" aria-label="프로젝트 검색" /></label>
          <section className="oc-projects" aria-labelledby="oc-projects-label"><header><strong id="oc-projects-label">최근 프로젝트</strong><small>{privateSidebarProjects.length}/{privateProjects!.length}</small></header><nav className="oc-project-switcher" aria-label="프로젝트 전환">{privateSidebarProjects.map((item) => { const selected = item.project.id === privateOnlyProject.project.id; return <div className="oc-project-row" data-selected={selected ? 'true' : undefined} key={item.project.id}><button className="oc-project-select" data-private-project={item.project.id} aria-label={item.project.name} aria-current={selected ? 'page' : undefined} onClick={() => switchPrivateProject(item.project.id)}><i aria-hidden="true" /><span>{item.project.name}</span></button><button className="oc-project-menu" type="button" disabled aria-label={`${item.project.name} 프로젝트 메뉴 · 준비 중`} title="프로젝트 메뉴 · 준비 중"><MoreHorizontal size={18} aria-hidden="true" /></button></div> })}{privateSidebarProjects.length === 0 && <p className="oc-project-empty">일치하는 프로젝트가 없습니다.</p>}</nav></section>
          <nav className="oc-management" aria-label="관리">{workspaceManagementItems.map((item) => <button key={item.id} type="button" disabled aria-label={`${item.label} · 준비 중`}>{item.id === 'archive' ? <Archive size={18} aria-hidden="true" /> : <Plug size={18} aria-hidden="true" />}<span>{item.label}</span><small>준비 중</small></button>)}</nav></div>
        {onLogout ? <button className="oc-nav-account" type="button" data-private-logout="true" onClick={() => void onLogout()}><UserRound size={18} aria-hidden="true" /><span><strong>Cherry 계정</strong><small>로그아웃</small></span></button> : <a className="oc-nav-account" href="/workspace" onClick={() => closePrivateNavigation()}><UserRound size={18} aria-hidden="true" /><span><strong>로그인 또는 계정 관리</strong><small>비공개 워크스페이스</small></span></a>}
      </aside>
      <main ref={contentRef} id="oc-main-content" className="oc-dashboard-content" tabIndex={-1}><header className="oc-topbar"><button ref={menuButtonRef} className="oc-nav-trigger" aria-label="전역 탐색 열기" aria-expanded={navigationOpen} onClick={() => setNavigationOpen(true)}><Menu size={20} aria-hidden="true" /></button></header><div className="oc-primary-workspace"><CurrentProjection projection={privateOnlyProject.modelV2} /><PlannerConversation events={privateOnlyProject.modelV2.events} /></div><details className="oc-v1-compatibility"><summary><span>v1 호환 정보</span><small>현재 projection에는 호환 위계가 없습니다</small></summary><div className="oc-v1-compatibility__content" role="status"><h2>v1 호환 정보 없음</h2><p>서버가 제공한 호환 위계가 없어 페이즈·범위·스테이지를 대신 계산하지 않습니다.</p></div></details></main>
    </section>
  }
  const privateProjection = project ? privateProjects?.find((item) => item.project.id === project.project.id)?.modelV2 : undefined
  if (!data || !project) return <section className="cn-dashboard cn-loading"><h2>{error ?? 'OUTCOME 원본 묶음을 검증하고 있습니다'}</h2>{error && <button onClick={() => void load()}>다시 확인</button>}</section>
  const closeNavigation = (restoreFocus = false) => { setNavigationOpen(false); if (restoreFocus) window.requestAnimationFrame(() => menuButtonRef.current?.focus()) }; const switchProject = (id: string) => { setSelectedProjectId(id); setSelection(null); setMobileLevel(0); setStagesExpanded(false); closeNavigation() }
  const normalizedProjectQuery = projectQuery.trim().toLocaleLowerCase('ko-KR'); const sidebarProjects = normalizedProjectQuery ? dashboardProjects.filter((item) => item.project.name.toLocaleLowerCase('ko-KR').includes(normalizedProjectQuery)) : dashboardProjects
  const managementIcon = (id: (typeof workspaceManagementItems)[number]['id']) => id === 'archive' ? <Archive size={18} aria-hidden="true" /> : <Plug size={18} aria-hidden="true" />
  const current = currentHierarchy(project)
  if (privateProjection && (!current.phase || !current.scope || !current.stage)) return <section className="cn-dashboard oc-dashboard" data-project-id={project.project.id} data-compatibility-available="false">
    <a className="oc-skip-link" href="#oc-main-content">본문으로 건너뛰기</a>
    {navigationOpen && <button className="oc-nav-backdrop" aria-label="탐색 닫기" tabIndex={-1} onClick={() => closeNavigation(true)} />}
    <aside ref={navigationRef} className="oc-global-nav" data-open={navigationOpen ? 'true' : 'false'} aria-label="OUTCOME 전역 탐색" role={navigationOpen ? 'dialog' : undefined} aria-modal={navigationOpen ? true : undefined}>
      <header><span className="oc-nav-brand"><Layers3 size={20} aria-hidden="true" /><strong>OUTCOME</strong></span><button className="oc-nav-close" aria-label="탐색 닫기" onClick={() => closeNavigation(true)}><X size={20} aria-hidden="true" /></button></header>
      <div className="oc-nav-workspace"><button className="oc-new-project" type="button" disabled aria-label="새 프로젝트 · 준비 중"><Plus size={18} aria-hidden="true" /><span>새 프로젝트</span><small>준비 중</small></button>
        <label className="oc-project-search"><Search size={18} aria-hidden="true" /><span className="oc-visually-hidden">프로젝트 검색</span><input type="search" value={projectQuery} onChange={(event) => setProjectQuery(event.target.value)} placeholder="프로젝트 검색" aria-label="프로젝트 검색" /></label>
        <section className="oc-projects" aria-labelledby="oc-projects-label"><header><strong id="oc-projects-label">최근 프로젝트</strong><small>{sidebarProjects.length}/{dashboardProjects.length}</small></header><nav className="oc-project-switcher" aria-label="프로젝트 전환">{sidebarProjects.map((item) => { const selected = item.project.id === project.project.id; return <div className="oc-project-row" data-selected={selected ? 'true' : undefined} key={item.project.id}><button className="oc-project-select" data-private-project={item.project.id} aria-label={`${item.project.name} · ${sourceStateLabel(item.status)}`} aria-current={selected ? 'page' : undefined} onClick={() => switchProject(item.project.id)}><i className={item.status} aria-hidden="true" /><span>{item.project.name}</span><span className="oc-visually-hidden">{sourceStateLabel(item.status)}</span></button><button className="oc-project-menu" type="button" disabled aria-label={`${item.project.name} 프로젝트 메뉴 · 준비 중`} title="프로젝트 메뉴 · 준비 중"><MoreHorizontal size={18} aria-hidden="true" /></button></div> })}{sidebarProjects.length === 0 && <p className="oc-project-empty">일치하는 프로젝트가 없습니다.</p>}</nav></section>
        <nav className="oc-management" aria-label="관리">{workspaceManagementItems.map((item) => <button key={item.id} type="button" disabled aria-label={`${item.label} · 준비 중`}>{managementIcon(item.id)}<span>{item.label}</span><small>준비 중</small></button>)}</nav></div>
      {onLogout ? <button className="oc-nav-account" type="button" data-private-logout="true" onClick={() => void onLogout()}><UserRound size={18} aria-hidden="true" /><span><strong>Cherry 계정</strong><small>로그아웃</small></span></button> : <a className="oc-nav-account" href="/workspace" onClick={() => closeNavigation()}><UserRound size={18} aria-hidden="true" /><span><strong>로그인 또는 계정 관리</strong><small>비공개 워크스페이스</small></span></a>}
    </aside>
    <main ref={contentRef} id="oc-main-content" className="oc-dashboard-content" tabIndex={-1}>
      <header className="oc-topbar"><button ref={menuButtonRef} className="oc-nav-trigger" aria-label="전역 탐색 열기" aria-expanded={navigationOpen} onClick={() => setNavigationOpen(true)}><Menu size={20} aria-hidden="true" /></button></header>
      <div className="oc-primary-workspace"><CurrentProjection projection={privateProjection} /><PlannerConversation events={privateProjection.events} /></div>
      <details className="oc-v1-compatibility"><summary><span>v1 호환 정보</span><small>현재 projection에는 호환 위계가 없습니다</small></summary><div className="oc-v1-compatibility__content" role="status"><h2>v1 호환 정보 없음</h2><p>서버가 제공한 호환 위계가 없어 페이즈·범위·스테이지를 대신 계산하지 않습니다.</p></div></details>
    </main>
  </section>
  const resolved = resolveHierarchySelection(project, selection)
  if (!resolved || !current.phase || !current.scope || !current.stage) return <section className="cn-dashboard cn-loading"><h2>현재 위치 원본 근거가 없습니다</h2></section>
  const { phase: selectedPhase, scope: selectedScope, stage: selectedStage } = resolved; const exploring = hierarchyIsExploring(project, resolved.selection); const hero = projectHeroModel(project); const now = nowPresentation(project.now); const snapshot = snapshotPresentation(data.snapshot); const sourceLabel = snapshot?.sourceLabel ?? sourceStateLabel(project.status); const sourceTimePrefix = snapshot?.timePrefix ?? '원본 관측'; const sourceObservedAt = snapshot ? compactTime(data.snapshot!.capturedAt) : hero.freshness; const refreshLabel = snapshot?.refreshLabel ?? '원본 묶음 새로고침'; const liveBinding = data.snapshot?.liveSessionRelay === false ? null : selectLiveBinding(project.bindings); const phases = structuralPhaseModel(project)
  const timingBinding = project.bindings.find((binding) => binding.status === 'active' && binding.freshness === 'fresh' && binding.stageId === current.stage!.id) ?? null; const timing = timingPresentation(current.stage, timingBinding, current.stage.id, new Date(data.observedAt))
  const selectedSummary = selectedStage ? stageDetailSemantics(selectedStage, selectedStage.dependsOn.map((id) => { const dependency = findStage(project, id)?.stage; return dependency ? stagePresentation(dependency.id, dependency.title, dependency.purpose)[0] : id })) : null; const selectedGroups = selectedStage ? meaningfulGateGroups(selectedStage.gate.groups, selectedStage.gate.available) : []; const selectedProgress = selectedStage?.id === current.stage.id ? gateProgress(selectedStage) : null; const hiddenStageCount = selectedScope ? collapsedStageCount(selectedScope.stages, stagesExpanded, resolved.selection.stageId) : 0; const visibleStages = selectedScope?.stages.slice(hiddenStageCount) ?? []; const github = project.connectors.github
  const showCurrentStage = () => { setSelection(defaultHierarchySelection(project)); setMobileLevel(2); setStagesExpanded(false) }; const selectPhase = (id: string) => { setSelection(selectHierarchyPhase(project, id)); setMobileLevel(1); setStagesExpanded(false) }; const selectScope = (id: string) => { setSelection(selectHierarchyScope(project, resolved.selection, id)); setMobileLevel(2); setStagesExpanded(false) }; const selectStage = (id: string) => { setSelection(selectHierarchyStage(project, resolved.selection, id)); setMobileLevel(2) }
  const handleColumnKeys = (event: React.KeyboardEvent<HTMLButtonElement>, ids: string[], index: number, choose: (id: string) => void, column: number) => { const nextIndex = nextStageOptionIndex(event.key, index, ids.length); if (nextIndex !== null) { event.preventDefault(); choose(ids[nextIndex]); window.requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-column="${column}"] [role="option"][aria-selected="true"]`)?.focus()); return }; const target = event.key === 'ArrowRight' ? column + 1 : event.key === 'ArrowLeft' ? column - 1 : null; if (target && target >= 1 && target <= 3) { event.preventDefault(); setMobileLevel(target - 1); window.requestAnimationFrame(() => window.requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-column="${target}"] [role="option"][tabindex="0"]`)?.focus())) } }
  const currentBreadcrumb = `${phasePresentation(current.phase.id, current.phase.title, current.phase.purpose)[0]} → ${scopePresentation(current.scope.id, current.scope.title, current.scope.purpose)[0]} → ${stagePresentation(current.stage.id, current.stage.title, current.stage.purpose)[0]}`; const selectedBreadcrumb = [selectedPhase && phasePresentation(selectedPhase.id, selectedPhase.title, selectedPhase.purpose)[0], selectedScope && scopePresentation(selectedScope.id, selectedScope.title, selectedScope.purpose)[0], selectedStage && stagePresentation(selectedStage.id, selectedStage.title, selectedStage.purpose)[0]].filter(Boolean).join(' → ')

  const initializeGateDetails = (node: HTMLDetailsElement | null) => { if (node && node.dataset.defaultOpen === 'true' && node.dataset.initialized !== 'true') { node.open = true; node.dataset.initialized = 'true' } }
  return <section className="cn-dashboard oc-dashboard" data-project-id={project.project.id} data-current-phase-id={current.phase.id} data-selected-phase-id={selectedPhase?.id ?? ''} data-current-stage-id={current.stage.id} data-selected-stage-id={selectedStage?.id ?? ''} data-mobile-level={mobileLevel} data-snapshot-boundary={data.snapshot?.boundary ?? 'live_source'}>
    <a className="oc-skip-link" href="#oc-main-content">본문으로 건너뛰기</a>
    {navigationOpen && <button className="oc-nav-backdrop" aria-label="탐색 닫기" tabIndex={-1} onClick={() => closeNavigation(true)} />}
    <aside ref={navigationRef} className="oc-global-nav" data-open={navigationOpen ? 'true' : 'false'} aria-label="OUTCOME 전역 탐색" role={navigationOpen ? 'dialog' : undefined} aria-modal={navigationOpen ? true : undefined}>
      <header><span className="oc-nav-brand"><Layers3 size={20} aria-hidden="true" /><strong>OUTCOME</strong></span><button className="oc-nav-close" aria-label="탐색 닫기" onClick={() => closeNavigation(true)}><X size={20} aria-hidden="true" /></button></header>
      <div className="oc-nav-workspace"><button className="oc-new-project" type="button" disabled aria-label="새 프로젝트 · 준비 중"><Plus size={18} aria-hidden="true" /><span>새 프로젝트</span><small>준비 중</small></button>
        <label className="oc-project-search"><Search size={18} aria-hidden="true" /><span className="oc-visually-hidden">프로젝트 검색</span><input type="search" value={projectQuery} onChange={(event) => setProjectQuery(event.target.value)} placeholder="프로젝트 검색" aria-label="프로젝트 검색" /></label>
        <section className="oc-projects" aria-labelledby="oc-projects-label"><header><strong id="oc-projects-label">최근 프로젝트</strong><small>{sidebarProjects.length}/{data.projects.length}</small></header><nav className="oc-project-switcher" aria-label="프로젝트 전환">{sidebarProjects.map((item) => { const selected = item.project.id === project.project.id; return <div className="oc-project-row" data-selected={selected ? 'true' : undefined} key={item.project.id}><button className="oc-project-select" data-private-project={item.project.id} aria-label={`${item.project.name} · ${sourceStateLabel(item.status)}`} aria-current={selected ? 'page' : undefined} onClick={() => switchProject(item.project.id)}><i className={item.status} aria-hidden="true" /><span>{item.project.name}</span><span className="oc-visually-hidden">{sourceStateLabel(item.status)}</span></button><button className="oc-project-menu" type="button" disabled aria-label={`${item.project.name} 프로젝트 메뉴 · 준비 중`} title="프로젝트 메뉴 · 준비 중"><MoreHorizontal size={18} aria-hidden="true" /></button></div> })}{sidebarProjects.length === 0 && <p className="oc-project-empty">일치하는 프로젝트가 없습니다.</p>}</nav></section>
        <nav className="oc-management" aria-label="관리">{workspaceManagementItems.map((item) => <button key={item.id} type="button" disabled aria-label={`${item.label} · 준비 중`}>{managementIcon(item.id)}<span>{item.label}</span><small>준비 중</small></button>)}</nav></div>
      {onLogout ? <button className="oc-nav-account" type="button" data-private-logout="true" onClick={() => void onLogout()}><UserRound size={18} aria-hidden="true" /><span><strong>Cherry 계정</strong><small>로그아웃</small></span></button> : <a className="oc-nav-account" href="/workspace" onClick={() => closeNavigation()}><UserRound size={18} aria-hidden="true" /><span><strong>로그인 또는 계정 관리</strong><small>비공개 워크스페이스</small></span></a>}
    </aside>
    <main ref={contentRef} id="oc-main-content" className="oc-dashboard-content" tabIndex={-1}>
    <header className="oc-topbar"><button ref={menuButtonRef} className="oc-nav-trigger" aria-label="전역 탐색 열기" aria-expanded={navigationOpen} onClick={() => setNavigationOpen(true)}><Menu size={20} aria-hidden="true" /></button></header>
    <section id="oc-current-work" className={`oc-hero ${project.status}`} aria-labelledby="oc-project-title">
      <div className="oc-hero-title"><Layers3 size={22} aria-hidden="true" /><div><h1 id="oc-project-title">{hero.name}</h1><p>{hero.outcome}</p></div></div>
      <div className="oc-hero-meta"><span className={`oc-source ${project.status}`}><strong>{sourceLabel}</strong><small>{sourceTimePrefix} {sourceObservedAt}</small></span><button className="cn-refresh" onClick={() => void load()} aria-label={refreshLabel} title={refreshLabel}><RefreshCw size={16} /></button></div>
      {!privateProjection && <div className="oc-now-summary" data-now-status={project.now.status}><strong>{now.headline}</strong></div>}
      {!privateProjection && <div className="oc-bindings" role="group" aria-label="역할별 세션 관측">{project.bindings.map((binding) => { const live = liveBinding === binding; return <details key={binding.role} className={`oc-role-row ${binding.status}`} data-live={live ? 'true' : 'false'}><summary><strong>{roleLabel(binding.role)}</strong><span>{bindingHeroLabel(binding)}</span>{live && <span className="oc-live-signal" aria-label="실시간 활동"><i aria-hidden="true" /><b>실시간</b></span>}</summary><div className="oc-role-history"><p>버전 {binding.bindingVersion ?? 0} · 이력 {binding.historyCount} · {binding.stageId ?? '스테이지 연결 없음'}</p>{(binding.history ?? []).length ? <ol>{binding.history!.map((event, index) => <li key={`${event.action}-${event.after_version}-${index}`}><strong>{event.action}</strong><span>버전 {event.before_version}→{event.after_version} · {compactTime(event.occurred_at)} · {event.stage_id ?? binding.stageId ?? '스테이지 연결 없음'}</span></li>)}</ol> : <p>전환 이력 없음</p>}</div></details> })}</div>}
      {project.status !== 'valid' && <div className={`oc-warning ${project.status}`} role="status"><strong>{sourceStateLabel(project.status)}</strong><span>원본 묶음의 참조와 식별자를 다시 확인하세요.</span></div>}
    </section>
    {privateProjection && <div className="oc-primary-workspace"><CurrentProjection projection={privateProjection} /><PlannerConversation events={privateProjection.events} /></div>}
    <details className="oc-v1-compatibility" open={!privateProjection}>
      {privateProjection && <summary><span>v1 호환 정보</span><small>역할 연결과 기술 근거는 필요할 때만 확인</small></summary>}
      <div className="oc-v1-compatibility__content">
    <nav className="oc-workspace-tabs" aria-label="모바일 작업공간">{mobileWorkspaceTabs.map((label) => <button key={label} type="button" aria-current={workspaceTab === label ? 'page' : undefined} onClick={() => setWorkspaceTab(label)}>{label}</button>)}</nav>
    <section className="oc-workbench" aria-label="프로젝트 작업대" data-conversation-peer-breakpoint={desktopConversationBreakpoint - 1}>
      <div className="oc-map-workspace" data-workspace-panel="지도" data-workspace-active={workspaceTab === '지도' ? 'true' : 'false'}>
    <div className="oc-hierarchy-sticky">
      <div className="oc-structure-band" role="img" aria-label={`전체 진행 흐름 · 현재 페이즈 ${current.phaseIndex}/${current.phaseTotal} · ${phases.map((phase) => `${phase.index} ${structureStatusLabel(phase.status)}`).join(', ')}`} data-structure-signature={phases.map((phase) => `${phase.id}:${phase.complete}/${phase.stages}:${phase.status}`).join('|')}>
        <div className="oc-progress-summary"><strong>전체 진행 흐름</strong><span><Radio size={13} aria-hidden="true" />현재 페이즈 {current.phaseIndex} / {current.phaseTotal}</span></div>
        <span className="oc-project-progress-track" aria-hidden="true">{phases.map((phase) => <i key={phase.id} className={phase.status} data-phase-id={phase.id} data-state={phase.status} style={{ '--oc-phase-fill': `${phase.stages ? phase.complete / phase.stages * 100 : 0}%` } as CSSProperties} />)}</span>
        <span className="oc-phase-milestones" aria-hidden="true">{phases.map((phase) => <i key={phase.id} className={phase.current ? 'current' : ''}>{phase.index}</i>)}</span>
      </div>
      <header className="oc-map-header"><div className="oc-map-copy"><h2 id="oc-map-title">프로젝트 여정</h2><p data-current-signature>현재 단계 · {currentBreadcrumb}</p>{exploring && <p className="oc-exploration-breadcrumb">선택한 단계 · {selectedBreadcrumb} · 실제 현재 위치 유지</p>}</div><div className="oc-map-actions"><button className="oc-show-current-button" aria-label="실제 현재 스테이지 보기" onClick={showCurrentStage}><Radio size={15} aria-hidden="true" />현재 단계 보기</button><div className="oc-mobile-level"><span>탐색 · <strong>{mobileHierarchyLevels[mobileLevel]}</strong> · {mobileLevel + 1}/{mobileHierarchyLevels.length}</span>{mobileLevel > 0 && <button onClick={() => setMobileLevel((value) => Math.max(0, value - 1))}><ChevronLeft size={16} />이전 단계</button>}</div></div></header>
    </div>
    <section id="oc-outcome-map" className="oc-outcome-map" aria-labelledby="oc-map-title"><nav className="oc-mobile-breadcrumb" aria-label="탐색 층위">{mobileHierarchyLevels.map((label, index) => { const active = mobileLevel === index; return <button key={label} aria-current={active ? 'step' : undefined} onClick={() => setMobileLevel(index)}><strong>{label}</strong>{active && <small>선택 중</small>}</button> })}</nav>
      <div className="oc-map-columns">
        <section className="oc-map-column oc-map-phase" data-column="1" data-mobile-active={mobileLevel === 0 ? 'true' : 'false'}><header><h3>페이즈</h3><span>{project.phases.length}개</span></header><div role="listbox" aria-label="프로젝트 페이즈">{project.phases.map((phase, index) => { const selected = phase.id === selectedPhase?.id; const currentItem = phase.id === project.current?.phaseId; const model = phases[index]; return <button key={phase.id} role="option" tabIndex={selected ? 0 : -1} aria-selected={selected} aria-current={currentItem ? 'step' : undefined} data-phase-id={phase.id} data-state={model.status} onKeyDown={(event) => handleColumnKeys(event, project.phases.map((item) => item.id), index, selectPhase, 1)} onClick={() => selectPhase(phase.id)}><StageNode state={model.status === 'complete' ? 'complete' : 'pending'} current={currentItem} /><span><strong>{phasePresentation(phase.id, phase.title, phase.purpose)[0]}</strong><small>{structureStatusLabel(model.status)} · 범위 {phase.scopes.length}개</small></span><ChevronRight size={15} aria-hidden="true" /></button> })}</div></section>
        <section className="oc-map-column oc-map-scope" data-column="2" data-mobile-active={mobileLevel === 1 ? 'true' : 'false'}><header><h3>범위</h3><span>{selectedPhase?.scopes.length ?? 0}개</span></header>{selectedPhase?.scopes.length ? <div role="listbox" aria-label="선택 페이즈 범위">{selectedPhase.scopes.map((scope, index) => { const selected = scope.id === selectedScope?.id; const currentItem = scope.id === project.current?.scopeId; const state = deriveScopeState(scope, project.current?.scopeId); return <button key={scope.id} role="option" tabIndex={selected ? 0 : -1} aria-selected={selected} aria-current={currentItem ? 'step' : undefined} data-scope-id={scope.id} data-state={state} onKeyDown={(event) => handleColumnKeys(event, selectedPhase.scopes.map((item) => item.id), index, selectScope, 2)} onClick={() => selectScope(scope.id)}><StageNode state={state === 'complete' ? 'complete' : 'pending'} current={currentItem} /><span><strong>{scopePresentation(scope.id, scope.title, scope.purpose)[0]}</strong><small>{scope.stages.length ? `스테이지 ${scope.stages.length}개` : '스테이지 정의 대기'}</small></span><ChevronRight size={15} aria-hidden="true" /></button> })}</div> : <p className="oc-empty-state">범위 정의 대기</p>}</section>
        <section className="oc-map-column oc-map-stage" data-column="3" data-mobile-active={mobileLevel === 2 ? 'true' : 'false'}><header><h3>스테이지</h3><span>{selectedScope?.stages.length ?? 0}개</span></header>{hiddenStageCount > 0 && <button className="oc-stage-disclosure" aria-expanded={stagesExpanded} onClick={() => setStagesExpanded(true)}>완료된 스테이지 {hiddenStageCount}개 펼치기</button>}{visibleStages.length ? <div className="oc-map-stage-list" role="listbox" aria-label="선택 범위 스테이지">{visibleStages.map((stage, index) => { const selected = stage.id === selectedStage?.id; const currentItem = stage.id === project.current?.stageId; const sourceIndex = selectedScope!.stages.findIndex((item) => item.id === stage.id); return <button key={stage.id} role="option" tabIndex={selected ? 0 : -1} aria-selected={selected} aria-current={currentItem ? 'step' : undefined} data-stage-id={stage.id} data-state={stage.state} onKeyDown={(event) => handleColumnKeys(event, visibleStages.map((item) => item.id), index, selectStage, 3)} onClick={() => selectStage(stage.id)}><StageNode state={stage.state} current={currentItem} /><span><strong>{stagePresentation(stage.id, stage.title, stage.purpose)[0]}</strong><small>{entityStateLabel(stage.state)} · 스테이지 위치 {sourceIndex + 1}/{selectedScope!.stages.length}</small></span><ChevronRight size={15} aria-hidden="true" /></button> })}</div> : <p className="oc-empty-state">스테이지 정의 대기 · 완료 조건을 추론하지 않습니다.</p>}</section>
      </div>
      <details ref={initializeGateDetails} className="oc-gate-inspector" data-default-open="true" data-stage-state={selectedStage?.state ?? 'unknown'} data-gate-available={selectedStage?.gate.available ? 'true' : 'false'} data-gate-closed={selectedStage?.gate.closed ?? 0} data-gate-total={selectedStage?.gate.total ?? 0} aria-label="선택 스테이지 완료 조건"><summary><span><small>완료 조건</small><strong>{selectedStage ? stagePresentation(selectedStage.id, selectedStage.title, selectedStage.purpose)[0] : '스테이지 정의 대기'}</strong></span><span><em>{selectedStage ? entityStateLabel(selectedStage.state) : '근거 없음'}</em><b>{selectedStage ? selectedGateCount(selectedStage) : '근거 없음'}</b></span></summary><div className="oc-gate-content"><header>{selectedStage ? <p>{stagePresentation(selectedStage.id, selectedStage.title, selectedStage.purpose)[1]}</p> : <p>선택한 범위에 스테이지와 완료 조건이 아직 정의되지 않았습니다.</p>}</header>{selectedStage && selectedSummary && <><div className="oc-gate-count"><span><small>확인된 항목 / 전체</small><strong>{selectedGateCount(selectedStage)}</strong></span><em>{entityStateLabel(selectedStage.state)}</em></div>{selectedProgress?.available && <span className="oc-gate-gauge" role="img" aria-label={`현재 스테이지 완료 조건 ${selectedProgress.closed}/${selectedProgress.total}`}><i style={{ transform: `scaleX(${selectedProgress.scale})` }} /></span>}<p className="oc-detail-boundary">{selectedSummary.boundaryCopy}</p><section className="oc-inspector-gates"><h4>남은 완료 조건</h4>{selectedStage.gate.gates.some((gate) => !gate.closed) ? <ol>{selectedStage.gate.gates.filter((gate) => !gate.closed).map((gate) => <li key={gate.id}><b>{gate.id}</b><span>{gatePresentation(selectedStage.id, gate.id, gate.title)}</span></li>)}</ol> : <p>{selectedSummary.checkedCopy}</p>}</section>{selectedGroups.length > 0 && <section data-source-groups><h4>그룹별 확인</h4><div className="oc-groups">{selectedGroups.map((group) => <article key={group.code} data-generic="false"><span><strong>{group.primaryLabel}</strong><small>코드 {group.secondaryCode}</small></span><b>{group.closed}/{group.total}</b></article>)}</div></section>}</>}</div></details>
    </section>
      </div>
      <aside className="oc-approval-rail" data-workspace-panel="승인" data-workspace-active={workspaceTab === '승인' ? 'true' : 'false'} aria-labelledby="oc-approval-title"><h2 id="oc-approval-title">승인</h2><p>승인 요청이 관측되면 여기에 표시됩니다.</p><strong>승인 권한 위임 없음</strong></aside>
      <div className="oc-conversation-panel" data-workspace-panel="대화" data-workspace-active={workspaceTab === '대화' ? 'true' : 'false'}><PlannerConversation events={privateProjection?.events ?? []} /></div>
    </section>
    <details id="oc-technical-evidence" className="oc-technical"><summary><span>기술 증거</span><small>빌드·역할 연결·GitHub·근거 축</small></summary><div className="oc-technical-content"><div className="oc-build" aria-label="제공 중인 고정 빌드"><small>기술 증거 · 프로젝트 식별자 {project.project.id} · {data.build.repository}/{data.build.ref}</small><strong>커밋 {data.build.commit ?? '근거 없음'} · 트리 {data.build.tree ?? '근거 없음'}</strong><span>에셋 {data.build.asset ?? '근거 없음'} · {snapshot ? '배포 스냅샷이며 실시간 세션은 별도 연결 예정' : '실시간 현재 작업은 빌드에 고정되지 않음'}</span></div><section className="oc-timing-evidence" aria-label="시간 근거"><div><small>{timing.elapsed.label}</small><strong>{timing.elapsed.value}</strong>{timing.elapsed.basis && <span>{timing.elapsed.basis}</span>}</div><div><small>{timing.eta.label}</small><strong>{timing.eta.value}</strong></div></section><section className="oc-binding-evidence" aria-label="역할 연결 기술 증거"><h3>역할 연결 근거</h3>{project.bindings.map((binding) => <div key={binding.role}><strong>{roleLabel(binding.role)}</strong><span>{binding.stageId ?? '스테이지 연결 없음'} · 이력 {binding.historyCount} · 관측 {compactTime(binding.observedAt)}</span></div>)}</section><section className="oc-github" aria-label="GitHub 전달 근거 연결"><header><div><small>선택 연결 근거 · GitHub</small><strong>{github.adopted ? 'GitHub 연결 채택' : 'GitHub 연결 미채택'}</strong></div><span className={github.state}>{entityStateLabel(github.state)}</span></header><div>{githubEvidenceItems(github).map((item) => <article key={item.label} className={item.state}><small>{item.label}</small><strong>{item.value}</strong><span>{entityStateLabel(item.state)}</span></article>)}</div><p>완료 판정 권한 없음 · GitHub 활동은 완료 조건 충족이나 Cherry 승인이 아닙니다.</p></section>{selectedStage && <div className="oc-axes" aria-label="선택 스테이지 근거 축"><Axis label="구현" value={selectedStage.axes.implementation} /><Axis label="테스트" value={selectedStage.axes.test} /><Axis label="증거 확정" value={selectedStage.axes.evidence} /><Axis label="변화 관측" value={project.now.status} /></div>}</div></details>
      </div>
    </details>
    </main>
  </section>
}
