import { describe, expect, it } from 'vitest'
import { axisStateLabel, entityStateLabel, findStage, githubEvidenceItems, selectProject, sourceStateLabel, stageDetailSemantics, summarizeStage, type GithubConnector, type PackageProject, type PackageStage } from './OutcomeDashboard'
import { activityLabelKo, axisLabelKo, gatePresentation, groupPresentation, hierarchyLabels, loginErrorPresentation, phasePresentation, projectOutcomePresentation, roleLabel, stagePresentation } from './outcomeKorean'

const stage = (overrides: Partial<PackageStage> = {}): PackageStage => ({ id: 'stage-one', title: 'Stage One', purpose: 'Verify the result', dependsOn: [], gatePurpose: 'Stage One acceptance checklist', sourceState: 'present', state: 'active', gate: { gates: [{ id: 'G1', title: 'closed', closed: true, groupCode: 'G' }, { id: 'G2', title: 'remaining', closed: false, groupCode: 'G' }], groups: [{ code: 'G', name: '증거', closed: 1, total: 2 }], total: 2, closed: 1, available: true, sourceRef: 'GATES.md' }, axes: { implementation: 'active', test: 'pending', evidence: 'pending', independentQa: 'not_started', cherryAcceptance: 'pending', release: 'not_started' }, ...overrides })
const github = (overrides: Partial<GithubConnector> = {}): GithubConnector => ({ adopted: true, required: false, state: 'connected', repository: 'owner/repo', remoteName: 'origin', defaultBranch: 'main', completionAuthority: false, localCandidate: { state: 'available', branch: 'main', ahead: 15, behind: 0, sync: 'ahead' }, published: { state: 'connected', repository: 'owner/repo', ref: 'origin/main', detail: 'published' }, checks: { state: 'unknown' }, release: { state: 'unknown' }, ...overrides })
const project = (id: string, title: string): PackageProject => ({ status: 'valid', errors: [], observedAt: null, project: { id, name: title, outcome: `${title} outcome`, acceptanceAuthority: 'Cherry' }, connectors: { github: github() }, phases: [{ id: `${id}-phase`, title: 'Phase', purpose: 'Phase purpose', completion: null, scopes: [{ id: `${id}-scope`, title: 'Scope', purpose: 'Scope purpose', stages: [stage({ id: `${id}-stage` })] }] }], current: { phaseId: `${id}-phase`, scopeId: `${id}-scope`, stageId: `${id}-stage` }, next: null, bindings: [], now: { status: 'unbound', activity: null, observedAt: null, source: 'runtime_registry' }, progress: { available: false, reason: 'no_cross_stage_aggregate' } })

describe('OUTCOME Package dashboard', () => {
  it('project switch keeps Package truth isolated', () => { const projects = [project('cherry-note', 'Cherry Note'), project('outcome', 'OUTCOME')]; expect(selectProject(projects, 'outcome')?.project.outcome).toBe('OUTCOME outcome'); expect(selectProject(projects, 'cherry-note')?.project.outcome).toBe('Cherry Note outcome') })
  it('purpose funnel resolves Phase Scope and Stage from one project', () => { const value = project('outcome', 'OUTCOME'); const found = findStage(value, 'outcome-stage'); expect([found?.phase.purpose, found?.scope.purpose, found?.stage.purpose]).toEqual(['Phase purpose', 'Scope purpose', 'Verify the result']) })
  it('stage summary reports checkbox evidence without a completion percentage for an active Stage', () => { expect(summarizeStage(stage())).toEqual({ closed: 1, total: 2, remaining: [{ id: 'G2', title: 'remaining', closed: false, groupCode: 'G' }], confirmedPercent: null }) })
  it('stage summary makes no percentage without Gate evidence', () => { expect(summarizeStage(stage({ gate: { gates: [], groups: [], total: 0, closed: 0, available: false, sourceRef: null } })).confirmedPercent).toBeNull() })
  it('evidence layers remain separate from NOW activity', () => { const value = project('outcome', 'OUTCOME'); value.now.activity = 'many edits'; expect(value.progress.available).toBe(false); expect(findStage(value, value.current?.stageId)?.stage.axes.evidence).toBe('pending') })
  it('GitHub evidence keeps local published checks and release separate', () => { const items = githubEvidenceItems(github()); expect(items.map((item) => item.label)).toEqual(['로컬 후보', 'GitHub 게시', '자동 검사', '출시']); expect(items[0].value).toContain('15개 앞섬'); expect(items[1].value).toContain('origin/main'); expect(items[2].state).toBe('unknown'); expect(items[3].state).toBe('unknown') })
  it('GitHub evidence shows connected empty remote as not published', () => { const items = githubEvidenceItems(github({ repository: 'dltmddnr3/outcome', published: { state: 'not_published', repository: 'dltmddnr3/outcome', ref: 'origin/main', detail: 'empty_remote' } })); expect(items[1]).toEqual({ label: 'GitHub 게시', state: 'not_published', value: 'dltmddnr3/outcome · 빈 원격 저장소' }) })
  it('accessibility correction keeps source and entity vocabulary separate', () => { expect(sourceStateLabel('unknown')).toBe('원본 묶음 근거 없음'); expect(entityStateLabel('unknown')).toBe('근거 없음'); expect(entityStateLabel('stale')).toBe('관측 오래됨'); expect(entityStateLabel('queued')).toBe('진입 대기'); expect(entityStateLabel('locked')).toBe('선행 완료 조건 대기') })
  it('axis vocabulary keeps raw complete separate from Gate completion without Gate evidence', () => { const value = stage({ gate: { gates: [], groups: [], total: 0, closed: 0, available: false, sourceRef: null }, axes: { implementation: 'not_sourced', test: 'complete', evidence: 'pending', independentQa: 'not_started', cherryAcceptance: 'pending', release: 'not_started' } }); expect(summarizeStage(value).confirmedPercent).toBeNull(); expect(axisStateLabel(value.axes.test)).toBe('완료'); expect(axisStateLabel(value.axes.test)).not.toBe(entityStateLabel('complete')) })
  it('axis vocabulary labels observed NOW states without completion-condition language and fails closed for untranslated values', () => { expect(['active', 'idle', 'stale', 'unbound', 'unknown'].map(axisStateLabel)).toEqual(['진행 중', '대기 중', '관측 오래됨', '연결 없음', '근거 없음']); expect(axisStateLabel('work_in_progress_not_candidate')).toBe('원본 상태 한글화 대기') })
  it('Stage detail keeps locked Final Feed 10/10 as checkbox evidence, not completion', () => { const value = stageDetailSemantics(stage({ id: 'stage-final-feed', title: 'Final Feed', state: 'locked', dependsOn: ['physical-acceptance'], gate: { gates: Array.from({ length: 10 }, (_, index) => ({ id: `F${index + 1}`, title: 'checked', closed: true, groupCode: 'F' })), groups: [], total: 10, closed: 10, available: true, sourceRef: 'GATES.md' } }), ['실제 사용 승인']); expect(value.closed).toBe(10); expect(value.confirmedPercent).toBeNull(); expect(value.countLabel).toBe('체크됨 / 전체'); expect(value.boundaryCopy).toContain('실제 사용 승인'); expect(value.checkedCopy).not.toContain('증거가 모두 확정') })
  it('Stage detail keeps bottom-shell 9/9 evidence pending without completion', () => { const value = stageDetailSemantics(stage({ state: 'gates_closed_evidence_pending', gate: { gates: Array.from({ length: 9 }, (_, index) => ({ id: `S${index + 1}`, title: 'checked', closed: true, groupCode: 'S' })), groups: [], total: 9, closed: 9, available: true, sourceRef: 'GATES.md' } })); expect(value.closed).toBe(9); expect(value.confirmedPercent).toBeNull(); expect(value.boundaryCopy).toContain('증거 확정은 아직 대기'); expect(value.checkedCopy).not.toContain('증거가 모두 확정') })
  it('Stage detail retains completion semantics only for complete Stage', () => { const value = stageDetailSemantics(stage({ state: 'complete', gate: { gates: [{ id: 'G1', title: 'checked', closed: true, groupCode: 'G' }, { id: 'G2', title: 'checked', closed: true, groupCode: 'G' }], groups: [], total: 2, closed: 2, available: true, sourceRef: 'GATES.md' } })); expect(value.confirmedPercent).toBe(100); expect(value.countLabel).toBe('증거 확정 / 전체'); expect(value.checkedCopy).toContain('증거가 모두 확정') })
  it('Stage detail gives every non-complete state an honest boundary', () => { for (const state of ['locked', 'blocked', 'queued', 'pending', 'active', 'unknown', 'gates_closed_evidence_pending']) { const value = stageDetailSemantics(stage({ state }), ['이전 작업 단계']); expect(value.confirmedPercent).toBeNull(); expect(value.countLabel).toBe('체크됨 / 전체'); expect(value.boundaryCopy.length).toBeGreaterThan(20); expect(value.checkedCopy).not.toContain('증거가 모두 확정') } })
  it('한글 계층 labels use the approved five-level vocabulary', () => { expect(hierarchyLabels).toEqual(['프로젝트', '큰 단계', '범위', '작업 단계', '완료 조건']) })
  it('한글 운영 문구 covers roles states activity and source-facing fallbacks', () => { expect(['planner', 'builder', 'ux_product_qa', 'release_audit'].map(roleLabel)).toEqual(['기획', '구현', '사용성·제품 검수', '출시 감사']); expect(activityLabelKo('Stage 6 NEEDS_REVISION correction is active; fresh independent QA remains required')).toBe('6단계 수정 진행 중 · 새 독립 검수가 필요합니다'); expect(sourceStateLabel('conflict')).toBe('원본 묶음 충돌'); expect(groupPresentation('RA', 'RA')).toBe('완료 조건 그룹'); expect(stagePresentation('new-stage')).toEqual(['작업 단계 제목 한글화 대기', '작업 단계 목적 한글화 대기']) })
  it('기술 식별자 보존 keeps Package IDs and GitHub evidence unchanged beneath Korean presentation', () => { const value = project('outcome', 'OUTCOME'); const before = structuredClone(value); expect(phasePresentation(value.phases[0].id)).toEqual(['큰 단계 제목 한글화 대기', '큰 단계 목적 한글화 대기']); expect(projectOutcomePresentation(value.project.id, value.project.outcome)).toContain('인공지능'); expect(githubEvidenceItems(value.connectors.github)[1].value).toContain('owner/repo · origin/main'); expect(value).toEqual(before); expect(value.current?.stageId).toBe('outcome-stage') })
  it('현재 렌더 가능한 미완료 완료 조건은 모두 자연스러운 한글 설명을 갖는다', () => {
    const gateIds = [
      ['stage-33-physical-acceptance-boundary', 'P33A3'], ['stage-33-physical-acceptance-boundary', 'P33A4'], ['stage-33-physical-acceptance-boundary', 'P33A5'],
      ...Array.from({ length: 8 }, (_, index) => ['stage-ux-product-qa', `ANQ${index + 1}`]),
      ['stage-release-audit', 'RA6'], ['stage-release-audit', 'RA7'], ['stage-release-audit', 'RA8'],
      ...Array.from({ length: 6 }, (_, index) => ['stage-mvp-scope-closure', `MC${index + 4}`]),
      ['outcome-stage-8', 'C1'], ['outcome-stage-8', 'C2'],
    ]
    const presentations = gateIds.map(([stageId, gateId]) => gatePresentation(stageId, gateId))
    expect(gateIds).toHaveLength(22)
    expect(presentations.filter((value) => value.includes('한글화 대기'))).toEqual([])
  })
  it('현재 렌더되는 근거 축 값은 모두 자연스러운 한글 상태를 갖는다', () => {
    const values = ['complete_on_exact_1cdec3f_candidate', 'complete_523_foundation_248_docktests_and_signed_build_matrix', 'complete_receipt_87b4523_and_handoff_verified', 'exact_1cdec3f_frozen', 'complete_for_fresh_independent_review', 'not_started_preflight_hold']
    expect(values.map(axisLabelKo).filter((value) => value.includes('한글화 대기'))).toEqual([])
  })
  it('인증 오류 식별자를 사용자용 한글로 바꾼다', () => {
    expect(loginErrorPresentation('invalid_credentials')).toBe('접근 암호가 올바르지 않습니다.')
    expect(loginErrorPresentation('too_many_attempts')).toBe('로그인 시도가 너무 많습니다. 잠시 후 다시 시도해 주세요.')
    expect(loginErrorPresentation('unexpected_backend_code')).toBe('로그인하지 못했습니다.')
  })
})
